### ISSUE TITLE
[mso_tenant] module doesn't work with python3 when adding a tenant which already exists in MSO

### ISSUE THREAD

**Issue by kentwu1** [CiscoDevNet/ansible-mso#102]
I was testing with python 3.6. It works fine when python 2.7 is used. And below is the ansible code that triggered this error. I used common tenant here but any tenant that already exists in MSO will trigger the error.

- name: Add the common tenant
    mso_tenant:
      host: "{{ mso_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      tenant:  common
      display_name: common
      sites: [STLD_FAB1, STLD_FAB2]
      use_proxy: no
      use_ssl: yes
      validate_certs: no
      state: present

And here is the related error msg,
TASK [Add the common tenant] ***********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: '>' not supported between instances of 'dict' and 'dict'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mso_tenant_payload__gsgz4a8/ansible_mso_tenant_payload.zip/ansible/module_utils/network/aci/mso.py\", line 54, in issubset\nTypeError: unhashable type: 'dict'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1598042345.9378407-193767360609446/AnsiballZ_mso_tenant.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1598042345.9378407-193767360609446/AnsiballZ_mso_tenant.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1598042345.9378407-193767360609446/AnsiballZ_mso_tenant.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.aci.mso_tenant', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_mso_tenant_payload__gsgz4a8/ansible_mso_tenant_payload.zip/ansible/modules/network/aci/mso_tenant.py\", line 200, in <module>\n  File \"/tmp/ansible_mso_tenant_payload__gsgz4a8/ansible_mso_tenant_payload.zip/ansible/modules/network/aci/mso_tenant.py\", line 185, in main\n  File \"/tmp/ansible_mso_tenant_payload__gsgz4a8/ansible_mso_tenant_payload.zip/ansible/module_utils/network/aci/mso.py\", line 58, in issubset\n  File \"/tmp/ansible_mso_tenant_payload__gsgz4a8/ansible_mso_tenant_payload.zip/ansible/module_utils/network/aci/mso.py\", line 16, in cmp\nTypeError: '>' not supported between instances of 'dict' and 'dict'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by xinyuezhao** [comment]
@kentwu1 
Hi, would you mind use **ansible-galaxy collection install cisco-mso-1.0.0.tar.gz —force** to upgrade to the newly version?
In that version, mso_tenant module should work with both python2 and python3.

**Comment by kentwu1** [comment]
Just tried but the problem seems to be there still....I downloaded this cisco.mso:1.0.0 from yesterday so I assume it should be new enough. Below are the related output. Let me know if I still miss something then.

sh-4.4$ ansible-galaxy collection install cisco-mso-1.0.0.tar.gz  --force
Process install dependency map
Starting collection install process
Installing 'cisco.mso:1.0.0' to '/opt/ansible/.ansible/collections/ansible_collections/cisco/mso'
sh-4.4$ ansible-playbook ./mso-multi-cluster-playbook.yaml

PLAY [ACI Namespace Operator Playbook] *************************************************************************

TASK [Gathering Facts] *****************************************************************************************
ok: [localhost]

TASK [Query a schema] ******************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************
ok: [localhost] => {
    "query_result.current.displayName": "kent_kubefed"
}

TASK [Add a tenant] ********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: '>' not supported between instances of 'dict' and 'dict'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mso_tenant_payload_4kyk8cqh/ansible_mso_tenant_payload.zip/ansible/module_utils/network/aci/mso.py\", line 54, in issubset\nTypeError: unhashable type: 'dict'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1598481289.8386874-8643401647002/AnsiballZ_mso_tenant.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1598481289.8386874-8643401647002/AnsiballZ_mso_tenant.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1598481289.8386874-8643401647002/AnsiballZ_mso_tenant.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.aci.mso_tenant', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_mso_tenant_payload_4kyk8cqh/ansible_mso_tenant_payload.zip/ansible/modules/network/aci/mso_tenant.py\", line 200, in <module>\n  File \"/tmp/ansible_mso_tenant_payload_4kyk8cqh/ansible_mso_tenant_payload.zip/ansible/modules/network/aci/mso_tenant.py\", line 185, in main\n  File \"/tmp/ansible_mso_tenant_payload_4kyk8cqh/ansible_mso_tenant_payload.zip/ansible/module_utils/network/aci/mso.py\", line 58, in issubset\n  File \"/tmp/ansible_mso_tenant_payload_4kyk8cqh/ansible_mso_tenant_payload.zip/ansible/module_utils/network/aci/mso.py\", line 16, in cmp\nTypeError: '>' not supported between instances of 'dict' and 'dict'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by kentwu1** [comment]
BTW, this issue happens inside a container deployed on the k8s cluster. But I assume the upgrade command should be the same right?

**Comment by kentwu1** [comment]
With -vvv flag, I saw that its still using the mso_tenant.py under /usr/local/lib/python3.6/site-packages/ansible/modules/network/aci/mso_tenant.py while the ansible-galaxy upgrade was done at /opt/ansible/.ansible/collections/ansible_collections/cisco/mso/plugins/modules/. I changed the ansible.cfg file to point to the upgraded path then its working now. I think you can close this issue now. Thx.

**Comment by lhercot** [comment]
Make sure when you call the modules to use the FQCN which is cisco.mso.mso_tenant and not just the module name as the module name will only call the integrated version.
We will also have to install the collection in that container so we keep it with latest release.

**Comment by kentwu1** [comment]
ok will try. Also is that possible we can make this release part of the integrated release then?
