### ISSUE TITLE
Error when removing BD

### ISSUE THREAD

**Issue by lhercot** [CiscoDevNet/ansible-mso#108]
Reporter: Kent Wu @kentwu1

Error when trying to remove the BD name test:
failed: [localhost] (item={u'subnets': [], u'displayName': u'test', u'name': u'test', u'bdRef': u'/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/test', u'l2Stretch': True, u'optimizeWanBandwidth': True, u'l2UnknownUnicast': u'proxy', u'intersiteBumTrafficAllow': True, u'vrfRef': u'/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S'}) => {"ansible_loop_var": "item", "changed": true, "current": {}, "data": [{"op": "remove", "path": "/templates/Fab1/bds/test"}], "info": {"body": "{\"code\":142,\"message\":\"Invalid Reference: Unable to find BD 'BdRef(5f612daaef0000438dd6106a,Fab1,test)' \"}", "connection": "close", "content-language": "en", "content-length": "106", "content-type": "application/json", "date": "Tue, 15 Sep 2020 23:07:38 GMT", "msg": "HTTP Error 400: Bad Request", "server": "nginx", "status": 400, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://10.66.176.111/api/v1/schemas/5f612daaef0000438dd6106a", "x-ratelimit-limit": "-1", "x-ratelimit-remaining": "-1", "x-ratelimit-reset": "1559582945"}, "item": {"bdRef": "/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/test", "displayName": "test", "intersiteBumTrafficAllow": true, "l2Stretch": true, "l2UnknownUnicast": "proxy", "name": "test", "optimizeWanBandwidth": true, "subnets": [], "vrfRef": "/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S"}, "msg": "MSO Error 142: Invalid Reference: Unable to find BD 'BdRef(5f612daaef0000438dd6106a,Fab1,test)' ", "payload": {"code": 142, "message": "Invalid Reference: Unable to find BD 'BdRef(5f612daaef0000438dd6106a,Fab1,test)' "}}

BD test is present when querying:
The BD is there when I query it,
TASK [debug] ***************************************************************************************************
ok: [localhost] => {
"msg": "bd_result: [{u'subnets': [], u'displayName': u'aci-containers-k8s_c3f1-node-bd', u'name': u'aci-containers-k8s_c3f1-node-bd', u'bdRef': u'/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/aci-containers-k8s_c3f1-node-bd', u'l2Stretch': False, u'l2UnknownUnicast': u'proxy', u'vrfRef': u'/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S'}, {u'subnets': [], u'displayName': u'aci-containers-k8s_c4f1-node-bd', u'name': u'aci-containers-k8s_c4f1-node-bd', u'bdRef': u'/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/aci-containers-k8s_c4f1-node-bd', u'l2Stretch': False, u'l2UnknownUnicast': u'proxy', u'vrfRef': u'/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S'}, {u'subnets': [], u'displayName': u'aci-containers-k8s_c3f1-pod-bd', u'name': u'aci-containers-k8s_c3f1-pod-bd', u'bdRef': u'/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/aci-containers-k8s_c3f1-pod-bd', u'l2Stretch': False, u'l2UnknownUnicast': u'proxy', u'vrfRef': u'/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S'}, {u'subnets': [], u'displayName': u'test', u'name': u'test', u'bdRef': u'/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/test', u'l2Stretch': True, u'optimizeWanBandwidth': True, u'l2UnknownUnicast': u'proxy', u'intersiteBumTrafficAllow': True, u'vrfRef': u'/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S'}]"
}
its the last one called 'test',
{u'subnets': [], u'displayName': u'test', u'name': u'test', u'bdRef': u'/schemas/5f612daaef0000438dd6106a/templates/Fab1/bds/test', u'l2Stretch': True, u'optimizeWanBandwidth': True, u'l2UnknownUnicast': u'proxy', u'intersiteBumTrafficAllow': True, u'vrfRef': u'/schemas/5f612daaef0000438dd6106a/templates/Common/vrfs/K8S'

**Comment by kentwu1** [comment]
And here is my playbook code to reproduce this issue,

- name: Query all BDs on Fab1 template
    mso_schema_template_bd:
      host: "{{ mso_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Fab1
      state: query
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    register: bd_result
  - debug:
      msg: "bd_result: {{ bd_result }}"
  - name: Delete extra BDs on Fab1 template
    #ignore_errors: yes
    cisco.mso.mso_schema_template_bd:
      host: "{{ mso_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Fab1
      bd: "{{ item.name }}"
      #bd: test
      state: absent
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: '{{ bd_result.current }}'
    when: (bd_result is defined) and (item.name not in site_bds_dict['Fab1'])

**Comment by xinyuezhao** [comment]
@kentwu1 
Hi, would you mind share the playbook which creates those template and BDs so that we can reproduce your issue?

**Comment by kentwu1** [comment]
playbook provided and explained. Thx.

**Comment by xinyuezhao** [comment]
In this case, the template was deployed to a site and the 'test' BD which we fail to delete was created manually in UI, so this 'test' BD was created at both template and site level.

To remove this BD, we need first use ‘mso_schema_site_bd’ to delete the BD from site level, then use ‘mso_schema_template_bd’ to remove it from template level.

example here:
- name: Remove site BD test first
    cisco.mso.mso_schema_site_bd:
      host: "{{ mso_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      site: '{{ mso_site | default("ansible_test") }}'
      template: Fab1
      bd: test
      use_proxy: no
      use_ssl: yes
      validate_certs: no
      state: absent
    register: nm_remove_site_bd_2
    
  - name: Delete test BD on Fab1 template
    cisco.mso.mso_schema_template_bd:
      host: "{{ mso_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Fab1
      bd: test
      state: absent
      use_proxy: no
      use_ssl: yes
      validate_certs: no
