### ISSUE TITLE
Current public docs for mso_schema_site_anp_epg_staticport do not list out type choices

### ISSUE THREAD

**Issue by cunningr** [CiscoDevNet/ansible-mso#109]
The documentation here: https://docs.ansible.com/ansible/latest/modules/mso_schema_site_anp_epg_staticport_module.html

is not showing all the new options for 'type:'

it would be good to get those updated!

**Comment by lhercot** [comment]
I see it present now in the page so it seems to be resolved. Can you confirm so we can close this issue?

**Comment by cunningr** [comment]
looks good.  Thank you!
