### ISSUE TITLE
Error Removing EPG

### ISSUE THREAD

**Issue by kmrobert** [CiscoDevNet/ansible-mso#111]
Similar to issue #108 

    - name: Remove EPGs
      cisco.mso.mso_schema_template_anp_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no
        schema: SOME_SCHEMA
        template: DC_SOMEDC
        anp: SOME_AP
        epg: VL3368_EPG
        display_name: VL3368_EPG
        bd:
          name: VL3368_BD
        state: absent
      delegate_to: localhost

Output:

fatal: [mso-vm -> localhost]: FAILED! => {
    "changed": true,
    "current": {},
    "data": [
        {
            "op": "remove",
            "path": "/templates/DC_SOMEDC/anps/SOME_AP/epgs/VL3368_EPG"
        }
    ],
    "info": {
        "body": "{\"code\":142,\"message\":\"Invalid Reference: Unable to find EPG 'EpgRef(5f3bee91120000cc5ea4e546,DC_SOMEDC,SOME_AP,VL3368_EPG)' \"}",
        "connection": "close",
        "content-language": "en",
        "content-length": "130",
        "content-type": "application/json",
        "date": "Tue, 29 Sep 2020 14:11:34 GMT",
        "msg": "HTTP Error 400: Bad Request",
        "server": "nginx",
        "status": 400,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://mso-vm/api/v1/schemas/5f3bee91120000cc5ea4e546"
    },
    "invocation": {
        "module_args": {
            "anp": "SOME_AP",
            "bd": {
                "name": "VL3368_BD",
                "schema": null,
                "template": null
            },
            "display_name": "VL3368_EPG",
            "epg": "VL3368_EPG",
            "host": "mso-vm",
            "intersite_multicaste_source": null,
            "intra_epg_isolation": null,
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "preferred_group": null,
            "protocol": "https",
            "schema": "SOMESCHEMA",
            "state": "absent",
            "subnets": null,
            "template": "DC_SOMEDC",
            "timeout": 30,
            "use_proxy": true,
            "use_ssl": true,
            "useg_epg": null,
            "username": "admin",
            "validate_certs": false,
            "vrf": null
        }
    },
    "msg": "MSO Error 142: Invalid Reference: Unable to find EPG 'EpgRef(5f3bee91120000cc5ea4e546,DC_SOMEDC,SOME_AP,VL3368_EPG)' ",
    "payload": {
        "code": 142,
        "message": "Invalid Reference: Unable to find EPG 'EpgRef(5f3bee91120000cc5ea4e546,DC_SOMEDC,SOME_AP,VL3368_EPG)' "

**Comment by xinyuezhao** [comment]
Hi, @kmrobert 

This issue could happen if your EPG was created manually and your template was deployed to a site. 

In this case, the EPG exist at both site and template level. To delete it, you need first use 'cisco.mso.mso_schema_site_anp_epg' to delete it from site level and then use 'cisco.mso.mso_schema_template_anp_epg' to delete it from template level.

**Comment by xinyuezhao** [comment]
Hi, we are going to close this issue.
If the solution above doesn't resolve your problem, feel free to open the issue again.
