### ISSUE TITLE
cannot apply global contract from other schema

### ISSUE THREAD

**Issue by ccie9773** [CiscoDevNet/ansible-mso#114]
task:
---
    - name: Add contract to EPG-Y1
      cisco.mso.mso_schema_template_anp_epg_contract:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "no"
        #schema: "{{ schema }}"
        schema: tenant-y-Schema
        template: "{{ template }}"
        #anp: "{{ anp }}"
        #epg: "{{ epg2 }}"
        anp: "ap-y"
        epg: "epg-y1"
        contract:
          name: "{{ contract }}"
          type: consumer
        state: present
      delegate_to: localhost

{{contract}} is configured in another schema(different tenant). it works on MSO GUI.

failure log:

fatal: [mso]: FAILED! => {
    "changed": true,
    "current": {
        "contractRef": {
            "contractName": "contract-by",
            "schemaId": "5f7bd1d038000013192eb7a1",
            "templateName": "Template1"
        },
        "relationshipType": "consumer"
    },
    "data": [
        {
            "op": "add",
            "path": "/templates/Template1/anps/ap-y/epgs/epg-y1/contractRelationships/-",
            "value": {
                "contractRef": {
                    "contractName": "contract-by",
                    "schemaId": "5f7bd1d038000013192eb7a1",
                    "templateName": "Template1"
                },
                "relationshipType": "consumer"
            }
        }
    ],
    "info": {
        "body": "{\"code\":142,\"message\":\"Invalid Reference: The consumer contract contract-by on EPG 'epg-y1' is invalid\"}",
        "connection": "close",
        "content-language": "en",
        "content-length": "104",
        "content-type": "application/json",
        "date": "Tue, 06 Oct 2020 02:48:53 GMT",
        "msg": "HTTP Error 400: Bad Request",
        "server": "nginx",
        "status": 400,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://100.64.60.51/api/v1/schemas/5f7bd1d038000013192eb7a1"
    },
    "invocation": {
        "module_args": {
            "anp": "ap-y",
            "contract": {
                "name": "contract-by",
                "schema": "tenant-y-Schema",
                "schema_id": "5f7bd1d038000013192eb7a1",
                "template": "Template1",
                "type": "consumer"
            },
            "epg": "epg-y1",
            "host": "100.64.60.51",
            "login_domain": null,
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "protocol": "https",
            "schema": "tenant-y-Schema",
            "state": "present",
            "template": "Template1",
            "timeout": 30,
            "use_proxy": true,
            "use_ssl": true,
            "username": "admin",
            "validate_certs": false
        }
    },
    "msg": "MSO Error 142: Invalid Reference: The consumer contract contract-by on EPG 'epg-y1' is invalid",
    "payload": {
        "code": 142,
        "message": "Invalid Reference: The consumer contract contract-by on EPG 'epg-y1' is invalid"
    }
}

**Comment by anvitha-jain** [comment]
@ccie9773 
{{contract}} configured in another schema(different tenant), it works on MSO GUI and through the playbook.
Your error was regenrated and the problem was in the below section

- name: Ensure contract-by exist
    mso_schema_template_contract_filter:
      host: mso-host
      username: user
      password: pwd
      use_proxy: true
      output_level: info
      validate_certs: false
      use_ssl: true
      schema: tenant-y-Schema     #value improper ( Suppose to give current schema )
      template: Template1     #value improper ( Suppose to give current template )
      contract: contract-by
      filter: Filter-test       #filter-name from the other schema and template of which contract you want to use
      filter_schema: Schema-test        #schema-name where the filter is present,
      filter_template: Template-test   #template-name where the filter is present,
      state: present

When you are creating a contract that already exist you need to input filter, filter_schema and filter_template parameters from the preexisting contract you want to use, but the parameters  for schema and template has to be the current values, to make the contract available for current EPG.
