### ISSUE TITLE
[mso_schema_site_external_epg] Add capability to set L3Out mapping at Site Level

### ISSUE THREAD

**Issue by lhercot** [CiscoDevNet/ansible-mso#119]
Currently External EPG to L3Out can be mapped at template level but not at Site level.
This ask is to add a new module called mso_schema_site_external_epg allowing to set that mapping.

**Comment by GaetanoCarlucci** [comment]
I thought this module was built for this purpose **mso_schema_site_external_epg_selector**
https://github.com/CiscoDevNet/ansible-mso/blob/master/plugins/modules/mso_schema_site_external_epg_selector.py

what is the purpose of this module then?

**Comment by lhercot** [comment]
@GaetanoCarlucci,the mso_schema_site_external_epg_selector is specifically for Cloud External EPGs, to define which IP / Subnet is mapped to the Cloud External EPG.

**Comment by GaetanoCarlucci** [comment]
I see, so we use it in combination with cloud apic, right?

**Comment by lhercot** [comment]
Correct.

**Comment by lhercot** [comment]
We are currently freezing the work on this issue as we are blocked by a check present in the API.
Cisco is internally working on solving that issue on the API side.
In the meantime, this can be achieve using the mso_rest call which would include the template level add and the site level information using PATCH API.
