### ISSUE TITLE
Added region and CIDR support for site local VRF

### ISSUE THREAD

**Issue by aciguru** [CiscoDevNet/ansible-mso#12]
**SUMMARY**
Added support for adding region and Primary CIDR for site-local VRF.

**ISSUE OPENER** devarshishah3

**ISSUE TYPE**
Bugfix Pull Request

**COMPONENT NAME**
mso_schema_site_vrf.py

**ADDITIONAL INFORMATION**

**Comment by aciguru** [comment]
https://github.com/ansible/ansible/pull/62644

**Comment by lhercot** [comment]
Closing because module already exist for it.
Please test the mso_schema_site_vrf_region, mso_schema_site_vrf_region_cidr and mso_schema_site_vrf_region_subnet.

Let us know if anything is missing.
