### ISSUE TITLE
mso_schema module generates an invalid POST request.

### ISSUE THREAD

**Issue by niekvn1** [CiscoDevNet/ansible-mso#123]
When the first example on [this Doc Page](https://docs.ansible.com/ansible/latest/collections/cisco/mso/mso_schema_module.html#parameter-templates) is used. The MSO will return the following error:

```
"msg":"MSO Error 125: Malformed body",
"payload":{
   "code":125,
   "info":{
      "obj[0]":[
         "\"{'displayName': 'template1', 'name': 'template1', 'tenantId': 'north_europe'}\" is not an object"
      ]
   },
   "message":"Malformed body"
}
```

I discussed this problem in [this post](https://groups.google.com/g/ansible-project/c/on64onW7MSU) in the Ansible mailing list, where someone noticed that this bug was introduced in commit [98f010a6889c45536b925a0b77a99e816922929e](https://github.com/CiscoDevNet/ansible-mso/commit/98f010a6889c45536b925a0b77a99e816922929e), by setting the element type of the template list to string instead of dict.

**Comment by felixfontein** [comment]
It's this particular one: https://github.com/CiscoDevNet/ansible-mso/commit/98f010a6889c45536b925a0b77a99e816922929e#diff-888947ea7d10c734b2aa126e64d6c21f7e9c61cf89fd17e644cba7f9682a0990R116

**Comment by siemhermans** [comment]
So instead of fixing the type of the return value, the feature to create a schema was removed altogether. How exactly does this solve the issue @lhercot @xinyuezhao?

**Comment by xinyuezhao** [comment]
Hi,
As this [note](https://github.com/CiscoDevNet/ansible-mso/blob/e0d35834bbd7e5d566dfa193360a7f4ef3acd887/plugins/modules/mso_schema.py#L36) in documentation, we would recommend you to use 'mso_schema_template' module. In mso_schema_template module, the schema will be created automatically with template.

If you want to do exactly the same thing as first example you mentioned, you may want to use mso_rest module to do that. This mso_rest module will be included in our next release which should be available early next week.
