### ISSUE TITLE
[mso_schema_template] Issue when using spaces in template names.

### ISSUE THREAD

**Issue by patrickspaans** [CiscoDevNet/ansible-mso#125]
When using a template name without a space in it, this module works as intended, but when the template name contains a space, an error occurs when running the module if said template already exists.

If I try to create a template named 'test template' using this module, and it already exists, it will throw an error containing the following error message:

`MSO Error 400: Bad Request: Template name in schema schema1 must be unique
`

When the template is named 'testtemplate' and already exists, no such error message is shown and the module behaves as expected (with no changes being made and it being listed as 'ok').

**Comment by shrsr** [comment]
@patrickspaans 
1. Which version of MSO are you using?
2. Can you please share the playbook where you came across this issue?
3. Can you please use the latest collection, If you don't already have one?

**Comment by patrickspaans** [comment]
The MSO version I'm using is 3.0(3l).

I was using the following playbook:

`- name: Add a new template
  hosts: mso
  connection: local
  gather_facts: false

  vars:
    aci_login: &mso_login
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"

  tasks:
    - name: Create a new template
      cisco.mso.mso_schema_template:
        <<: *mso_login
        template: "template name with spaces"
        display_name: "placeholder"
        schema: "testschema"
        tenant: "testtenant"
        state: present
`

And I already have the latest version of cisco.mso installed.

**Comment by shrsr** [comment]
Can you share the actual playbook with all tasks until you come across the error?

I'm unable to reproduce the error at my end. I only come across an error when I try to use the same display name for two different templates.

**Comment by patrickspaans** [comment]
I forgot to copy the opening '---' along with it, but it is the entire playbook used.

```
---

- name: Add a new template
  hosts: mso
  connection: local
  gather_facts: false

  vars:
    aci_login: &mso_login
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"

  tasks:
    - name: Create a new template
      cisco.mso.mso_schema_template:
        <<: *mso_login
        template: "template name with spaces"
        display_name: "placeholder"
        schema: "testschema"
        tenant: "testtenant"
        state: present
```

When executing this playbook, I get the following output:

```
*****$ ansible-playbook -i inventory.yml mso_template.yml                                                                                                                           PLAY [Add a new template] **********************************************************************************************                                                                                                                        TASK [Create a new template] *******************************************************************************************
changed: [mso1]                                                                                                                                                                                                                                 PLAY RECAP *************************************************************************************************************
mso1                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0       

*****$ ansible-playbook -i inventory.yml mso_template.yml                                                                                                                           PLAY [Add a new template] **********************************************************************************************                                                                                                                        TASK [Create a new template] *******************************************************************************************
fatal: [mso1]: FAILED! => {"changed": true, "current": {"displayName": "placeholder", "name": "template name with spaces", "tenantId": "5fbce21b3600004fac11496b"}, "data": [{"op": "add", "path": "/templates/-", "value": {"displayName": "placeholder", "name": "template name with spaces", "tenantId": "5fbce21b3600004fac11496b"}}], "info": {"body": "{\"code\":400,\"message\":\"Bad Request: Template name in schema testschema must be unique\"}", "connection": "close", "content-language": "en", "content-length": "87", "content-type": "application/json", "date": "Wed, 25 Nov 2020 11:56:34 GMT", "msg": "HTTP Error 400: Bad Request", "server": "nginx", "status": 400, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://*****/api/v1/schemas/5fbce21d3c000084b9a6edd3"}, "msg": "MSO Error 400: Bad Request: Template name in schema testschema must be unique", "payload": {"code": 400, "message": "Bad Request: Template name in schema testschema must be unique"}}                                                                                                                                                                                                         PLAY RECAP *************************************************************************************************************mso1                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0      
```

As you can see, the first time I execute it, it works fine, but the second time it fails as the template already exists. (II had removed the template before this test)

**Comment by shrsr** [comment]
---

- name: Add a new template
  hosts: mso
  connection: local
  gather_facts: false

  vars:
    mso_login: &mso_login
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"

  tasks:
    - name: Create a new template
      cisco.mso.mso_schema_template:
        <<: *mso_login
        template: "template name with spaces"
        display_name: "placeholder"
        schema: "testschema"
        tenant: "testtenant"
        state: present

  - name: Create above template again
      cisco.mso.mso_schema_template:
        <<: *mso_login
        template: "template name with spaces"
        display_name: "placeholder"
        schema: "testschema"
        tenant: "testtenant"
        state: present






Can you run the above playbook with the command **ansible-playbook -i inventory.yml mso_template.yml -vvv**

**Comment by patrickspaans** [comment]
Using that playbook, I have the exact same issue.

[result.txt](https://github.com/CiscoDevNet/ansible-mso/files/5598375/result.txt)

**Comment by shrsr** [comment]
Can you please share the code in the module mso_schema_template.py in your collections?
Want to make sure that there's no discrepancy.

**Comment by patrickspaans** [comment]
Hereby the code. (Zipped due to not being able to upload .py files directly).
[mso_schema_template.zip](https://github.com/CiscoDevNet/ansible-mso/files/5598707/mso_schema_template.zip)

**Comment by shrsr** [comment]
Can you please add: **output_level: debug** to the playbook as mentioned below for both the tasks and give us the output file?

name: Create a new template
cisco.mso.mso_schema_template:
<<: *mso_login
template: "template name with spaces"
output_level: debug
display_name: "placeholder"
schema: "testschema"
tenant: "testtenant"
state: present

**Comment by patrickspaans** [comment]
[result.txt](https://github.com/CiscoDevNet/ansible-mso/files/5599197/result.txt)

**Comment by shrsr** [comment]
@patrickspaans 
Can you query the template after you create it the first time and share the result?

name: Query a new template
cisco.mso.mso_schema_template:
<<: *mso_login
template: "template name with spaces"
output_level: debug
schema: "testschema"
tenant: "testtenant"
state: query

**Comment by patrickspaans** [comment]
It fails, as the template doesn't exist.
[result.txt](https://github.com/CiscoDevNet/ansible-mso/files/5620945/result.txt)

However, when I remove the spaces like this:

 - name: Query a new template
      cisco.mso.mso_schema_template:
        <<: *mso_login
        template: "templatenamewithspaces"
        output_level: debug
        schema: "testschema"
        tenant: "testtenant"
        state: query

Then I'm able to query it.
[resultnospace.txt](https://github.com/CiscoDevNet/ansible-mso/files/5620946/resultnospace.txt)

I'm also making use of AWX, and I'm experiencing exactly the same issue there, so I assume the MSO itself is the cause.

**Comment by lhercot** [comment]
@patrickspaans Could you retry with the latest version?

We have changed the way we handle template name to match the MSO UI behavior. It means that the template name will be striped of the spaces but the display name should stay with a space.

**Comment by patrickspaans** [comment]
Thank you, this resolved the issue!
