### ISSUE TITLE
One Time Password with RSA Token Device MSO/Ansible issue

### ISSUE THREAD

**Issue by soumukhe** [CiscoDevNet/ansible-mso#139]
# When using One Time Password with RSA Token device (with Radius/AAA domain) it becomes very inconvinient for running Ansible Playbooks
 A playbook generally has many ansible modules, further you can concatinate playbooks and run them at one time
The default behavior is that every module in the playbook is a new login, so if you had 10 modules in the playbook, you have to acknowledge your RSA OTP Token 10 times.

In the future there is a plan to implement sharing of sessions as part of connection plugin effort 
(tracked at:  https://github.com/CiscoDevNet/ansible-aci/issues/25) but this is a long haul project and it is currently not planned before end of 2021.

# This is a workaround that can be used meanwhile.  Please see:
# https://github.com/soumukhe/MSO-OTP-RSA.git

**Comment by lhercot** [comment]
This should be fixed in v1.2.0 either by using the MSO HTTPAPI connection plugin or the ND HTTPAPI connection plugin (from cisco.nd collection).

See README for more instructions on how to use those.

Please let us know if that resolves that issue so we can close this issue.

**Comment by lhercot** [comment]
I will assume that this is fixed now. Please re-open an issue if it is not fixed.
