### ISSUE TITLE
mso_schema_template_external_epg always expects an L3out referenced

### ISSUE THREAD

**Issue by ddastoli** [CiscoDevNet/ansible-mso#144]
mso_schema_template_external_epg fails when an L3out is not present:
"ExternalEpg internet is missing L3Out on site AWS exception while trying to update schema"
If the ext epg is type cloud, an L3out should not be required.

See below for more details of the exception

ansible playbook:
--------------------
-
  name: create external epg
  hosts: localhost
  tasks:
    - include_vars: mso_variables.yml

    - name: Set vars
      set_fact: 
        mso_info: &mso_info
          host: '{{ mso_host }}'
          username: '{{ mso_user }}'
          password: '{{ mso_password }}'
          validate_certs: no

    - name: Add a selector to Azure external EPG
      cisco.mso.mso_schema_site_external_epg_selector:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        site: '{{ Azure_site }}'
        external_epg: internet
        selector: internet
        expressions:
          - type: ip_address
            operator: equals
            value: 0.0.0.0/0
        state: present

    - name: Add a selector to Azure external EPG
      cisco.mso.mso_schema_site_external_epg_selector:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        site: '{{ AWS_site }}'
        external_epg: internet
        selector: internet
        expressions:
          - type: ip_address
            operator: equals
            value: 0.0.0.0/0
        state: present

    # ADD external EPG
    - name: Add external EPG cloud
      cisco.mso.mso_schema_template_external_epg:
        <<: *mso_info
        schema: hybrid application
        template: cloud
        external_epg: internet
        type: cloud
        anp: 
          name: cloudAP
          template: cloud
          schema: hybrid application
        vrf:
          name: VRF1
          template: hybrid
          schema: hybrid application
        state: present
--------------------

Fault received with the execution of the play:
--------------------
fatal: [localhost]: FAILED! => {"changed": true, "current": {"anpRef": {"anpName": "cloudAP", "schemaId": "5fca454c530000184f2c20b5", "templateName": "cloud"}, "displayName": "internet", "extEpgType": "cloud", "name": "internet", "vrfRef": {"schemaId": "5fca454c530000184f2c20b5", "templateName": "hybrid", "vrfName": "VRF1"}}, "data": [{"op": "add", "path": "/templates/cloud/externalEpgs/-", "value": {"anpRef": {"anpName": "cloudAP", "schemaId": "5fca454c530000184f2c20b5", "templateName": "cloud"}, "displayName": "internet", "extEpgType": "cloud", "name": "internet", "vrfRef": {"schemaId": "5fca454c530000184f2c20b5", "templateName": "hybrid", "vrfName": "VRF1"}}}], "info": {"body": "{\"code\":400,\"message\":\"Bad Request: Patch Failed, Received: ExternalEpg internet is missing L3Out on site AWS exception while trying to update schema\"}", "connection": "close", "content-language": "en", "content-length": "151", "content-type": "application/json", "date": "Mon, 07 Dec 2020 08:13:24 GMT", "msg": "HTTP Error 400: Bad Request", "server": "nginx", "status": 400, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://173.36.219.157/api/v1/schemas/5fca454c530000184f2c20b5"}, "msg": "MSO Error 400: Bad Request: Patch Failed, Received: ExternalEpg internet is missing L3Out on site AWS exception while trying to update schema", "payload": {"code": 400, "message": "Bad Request: Patch Failed, Received: ExternalEpg internet is missing L3Out on site AWS exception while trying to update schema"}}

**Comment by ddastoli** [comment]
@lhercot followed also the generic test https://github.com/CiscoDevNet/ansible-mso/blob/master/tests/integration/targets/mso_schema_template_external_epg/tasks/main.yml but same result. I am on MSO 3.1.1g

**Comment by anvitha-jain** [comment]
This error is caused by MSO API functionality (MSO API error). Execution of above tasks (Creation of Ext EPGs at cloud site level) without L3out requires changes to be made in API.

**Comment by lhercot** [comment]
To add to Anvitha's answer. Today you will have to make that call with mso_rest to make the change at both the template and site level in one operation.
