### ISSUE TITLE
mso_schema_template_deploy status not showing changes not deployed to site

### ISSUE THREAD

**Issue by richardlock** [CiscoDevNet/ansible-mso#149]
cisco.mso collection 1.0.1
ansible 2.10.3

When using the cisco.mso.mso_schema_template_deploy module with state: status, it does not seem to return changed: true even when the site status reports that "Changes made in the template have not been deployed to site".  I have tested this by adding and saving a change in the GUI, but not deploying it to sites.

I'm writing a playbook to deploy various objects, but would like to add a task to check if there are any changes or issues in the schema template before deploying.

Thanks, Richard

Output from cisco.mso.mso_schema_template_deploy module with state: status.
```json
{
  "schema_template_status": {
    "changed": false,
    "current": {},
    "failed": false,
    "status": [
      {
        "schemaId": "removed",
        "siteId": "removed",
        "status": {
          "siteStatus": "Succeeded",
          "timestamp": 1608110341942,
          "timestampLocalDateTime": "2020-12-16T09:19:01"
        },
        "templateName": "removed"
      },
      {
        "schemaId": "removed",
        "siteId": "removed",
        "status": {
          "siteStatus": "Succeeded",
          "timestamp": 1608110341999,
          "timestampLocalDateTime": "2020-12-16T09:19:01"
        },
        "templateName": "removed"
      }
    ]
  }
}
```

**Comment by richardlock** [comment]
I'm happy to use another module if there's one which does return the status about changes.  I couldn't see it in any of the API output with Swagger either.

**Comment by shrsr** [comment]
@richardlock 
mso_schema_template_deploy has three states: deploy, undeploy and status
To begin with, let’s have a schema1 with Template1 and site1 associated with schema1. 
When we set state to deploy in the playbook: Template1 gets deployed to site1
Next, when we set state to status in the playbook: It shows us that template1 is deployed to site1
example: 	"status": [
        {
            "schemaId": "601b767f1000008f5cd8d368",
            "siteId": "5ef6807d0e0000cafd70fbe1",
            "status": {
                "siteStatus": "Succeeded",
                "timestamp": 1612415820333,
                "timestampLocalDateTime": "2021-02-04T05:17:00"
            },
            "templateName": "Template1"
        }
    ]

When, we set state to undeploy in the playbook: Template1 is undeployed from site1
When we set state to status in the playbook again: It shows the status as [], saying that it’s not been deployed

The ansible attribute "changed" here does not indicate whether a change has been made to the template.

That being said, when we add/change a template using other modules in mso using state: present the “changed” attribute does indicate whether the operation was successful.

Please let me know if you have any questions.

**Comment by richardlock** [comment]
Thanks Shreyas.  Is there a module which can detect if there are undeployed changes waiting to be deployed in a template?  I was wanting to have a safety check for people not to unknowingly deploy changes made by someone else but haven't been deployed to sites.  The same as a yellow exclamation mark in the MSO UI.

**Comment by shrsr** [comment]
@richardlock 
I have created a new module to check deployment status. Should be available on the next release.

**Comment by richardlock** [comment]
Thanks Shreyas
