### ISSUE TITLE
mso_schema_template_anp_epg Fails to Check without ANP

### ISSUE THREAD

**Issue by aciguru** [CiscoDevNet/ansible-mso#16]
SUMMARY
Running --check a full playbook from start to end of an ANP to BD to EPG to Contract on mso_schema_template_anp_epg fails when the ANP does not exist. Work around is to skip the check on this module.

ISSUE TYPE
Bug Report

COMPONENT NAME
mso_schema_template_anp_epg

ANSIBLE VERSION
2.8.1

EXPECTED RESULTS
This is hard to judge because it is a valid error but making the status change=true would be valid in most cases I believe during a check.

ACTUAL RESULTS
msg: 'Provided anp ''ANP_LAB'' does not exist. Existing anps: '

**Comment by aciguru** [comment]
https://github.com/ansible/ansible/issues/58603

**Comment by lhercot** [comment]
As said in the original thread, the current behavior is that our modules will fail if any pre-requisites are not satisfied at runtime.
This is true irrespective of check_mode.

If you want to avoid those errors, you can use the following workaround.
`ignore_errors: "{{ ansible_check_mode }}"`
This uses the boolean magic variable ansible_check_mode to bypass any error only when running in check_mode.

As we cannot know if the playbook contain the needed components (pre-requisites like ANP) we cannot infer the ids for the required elements and will fail. 

We took the decision not to change this behavior and I am closing this issue with a wontfix label.
