### ISSUE TITLE
mso_schema_template_contract_filter does not work for vrf scope

### ISSUE THREAD

**Issue by andyidau** [CiscoDevNet/ansible-mso#17]
The valid options for contract_scope are:

contract_scope=dict(type='str', choices=['application-profile', 'global', 'tenant', 'vrf'])

MSO permits all of these except 'vrf'. If the user specifies 'vrf', MSO expects the string 'context' to be sent instead.

**Comment by lhercot** [comment]
We will publish soon a new version of the collection that will include this change. In the meantime, you can get the nightly collection file from the latest CI/CD run (https://github.com/CiscoDevNet/ansible-mso/actions/runs/124056817).

You will need to install it using the ansible-galaxy collection command with the --force to update the code.
