### ISSUE TITLE
Host level variables not being used with ansible.netcommon.httpapi

### ISSUE THREAD

**Issue by netgirard** [CiscoDevNet/ansible-mso#215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* The README in this repo references using ansible_connection=ansible.netcommon.httpapi and ansible_network_os equal to either cisco.mso.mso or cisco.nd.nd to be able to omit the repeating connection arguments from each module invocation.  This does not appear to be working.  Also, that section of the README seems a little misleading, as it seems you have to use httpapi and cisco.nd.nd when you have an MSO deployment on top of Nexus Dashboard.

### Affected Module Name(s):

* mso_schema was specifically used, but assume all since this is probably in the mso module base class or lower.

### MSO version and MSO Platform

*  MSO v3.3.1.e on ND 2.0(2h)
* MSO v3.1.1i

### APIC version and APIC Platform for Site Level Resources

* N/A

### Collection versions

* v1.2.0 of cisco.mso
* v0.1.0 of cisco.nd

### Output/ Error message

* Variety of error messages depending on missing connection level attributes.  Errors are the same for the ND MSO (e__us1_mso) and standalone MSO (e_eu1_mso) which I did not include.
* fatal: [e_us1_mso]: FAILED! => {"attempts": 2, "changed": false, "current": {}, "msg": "Parameter 'password' is required for authentication"} 
* fatal: [e_us1_mso]: FAILED! => {"attempts": 2, "changed": false, "current": {}, "msg": "Authentication failed: Request failed: <urlopen error [Errno -2] Name or service not known>"}
* fatal: [e_us1_mso]: FAILED! => {"attempts": 2, "changed": false, "current": {}, "msg": "Authentication failed: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)>"}

### Expected Behavior

* Query succeeds

### Actual Behavior

* Query fails due to missing connection parameters

### Playbook tasks to Reproduce

* Inventory:
ansible-inventory -i inventory/engineering/engineering.ini --host e_us1_mso
{
    "ansible_connection": "ansible.netcommon.httpapi",
    "ansible_host": "10.x.x.x",
    "ansible_httpapi_use_proxy": false,
    "ansible_httpapi_use_ssl": true,
    "ansible_httpapi_validate_certs": false,
    "ansible_network_os": "cisco.nd.nd",
    "ansible_password": "<REMOVED>",
    "ansible_user": "admin",
}

* Error about missing password:
  name: Query all MSO Schema Information
  cisco.mso.mso_schema:
    state: query
  delegate_to: localhost
  retries: "{{ mso_retry }}"
  delay: 5
  register: schema_result
  until: schema_result is not failed

* Name or service unknown error:
  name: Query all MSO Schema Information
  cisco.mso.mso_schema:
    state: query
    password: "{{ ansible_password }}"
  delegate_to: localhost
  retries: "{{ mso_retry }}"
  delay: 5
  register: schema_result
  until: schema_result is not failed

* Certificate validation error:
  name: Query all MSO Schema Information
  cisco.mso.mso_schema:
    state: query
    password: "{{ ansible_password }}"
    host: "{{ ansible_host }}"
  delegate_to: localhost
  retries: "{{ mso_retry }}"
  delay: 5
  register: schema_result
  until: schema_result is not failed

* Successful
  name: Query all MSO Schema Information
  cisco.mso.mso_schema:
    state: query
    password: "{{ ansible_password }}"
    host: "{{ ansible_host }}"
    validate_certs: "{{ ansible_httpapi_validate_certs }}"
  delegate_to: localhost
  retries: "{{ mso_retry }}"
  delay: 5
  register: schema_result
  until: schema_result is not failed

### References

* #0000

**Comment by netgirard** [comment]
Looking around a bit more, looks like this might be fixed with PR #213 ?

**Comment by lhercot** [comment]
The latest ND and MSO collections should address this issue. Please reopen the issue if you still have problems with newly released version
