### ISSUE TITLE
Not seeing config deployed from Ansible in MSO or APIC GUI

### ISSUE THREAD

**Issue by mikel632** [CiscoDevNet/ansible-mso#219]
I am currently running MSO on a Nexus Dashboard VM cluster.

Ansible Version: 2.9.24
Nexus Dashboard Version: 2.1(1e)
MSO version: 3.3.1e
cisco.nd collection version 0.1.0
cisco.mso collection version 1.2.0

I run a playbook to configure a new ANP and deploy the template and it shows successful (i can even query the ANP afterword'), but it does not appear in the apic or mso gui. 

I have attached a text file showing the playbook and the results of my querying. After the playbooks ran the ANP was nowhere to be found in the mso gui or the apic gui
[cisco.mso galaxy collection issues.txt](https://github.com/CiscoDevNet/ansible-mso/files/7428312/cisco.mso.galaxy.collection.issues.txt)
.

**Comment by shrsr** [comment]
@mikel632 Prior to creating an ANP at site level using cisco.mso.mso_schema_site_anp, did you create ANP at template level using cisco.mso.mso_schema_template_anp?
Can you please share all the tasks you used in your playbook?

**Comment by shrsr** [comment]
@mikel632 Following up on my previous comment. Can you please tell me if you were able to deploy the config. based on my previous comment?

**Comment by lhercot** [comment]
Closing this issue as we didn't get any response since Dec 14th. Feel free to reopen an issue if you still have an issue.
