### ISSUE TITLE
Multiple modules don't work correctly when run with a user who only has the schemaEditor role

### ISSUE THREAD

**Issue by paul759** [CiscoDevNet/ansible-mso#227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you are using a user account that only has the schemaEditor role, there are a lot of features that don't work correctly with the ansible playbooks that you can do manually using the web interface.  

These features all seem to be related to looking up details in other areas of the application that the limited user is not allowed to administer.  

For example: the ansible modules cannot look up site ids and they cannot look up shared objects in other schemas (like common)

### Affected Module Name(s):

I have found issues with the following modules but I am sure it affects more than this.
* cisco.mso.mso_schema_site (and all the ones under that ie: cisco.mso.mso_schema_site_* ).  Basically anything that needs to look up the site id
* cisco.mso.mso_schema_template_anp_epg_contract (when trying to add a contract from a common schema)
* cisco.mso.mso_schema_template_anp_epg (when trying to use a BD from a common schema)
* cisco.mso.mso_schema_template_contract_filter (when trying to use a filter form a common schema)
* cisco.mso.mso_schema_template_bd (when trying to use a vrf from a common schema)
* cisco.mso.mso_schema_template_external_epg (when trying to use an l3out (and vrf) from a common schema)
* cisco.mso.mso_schema_template (when creating a new schema)

### MSO version and MSO Platform

I tested it using MSO V 3.0(3i) running in a Cisco DevNet Sandbox

### APIC version and APIC Platform for Site Level Resources

I didn't record it, but it was whatever is provided in the Cisco DevNet Sandbox.  Given the nature of the bug, I don't think it is relevant anyway.

### Collection versions

* cisco.mso 1.3.0

### Output/ Error message

It depends on the module, but these are some of the error messages that are received
* ```fatal: [localhost]: FAILED! => {"changed": false, "current": {}, "data": null, "info": {"body": "", "connection": "close", "content-length": "0", "date": "Mon, 10 Jan 2022 03:52:59 GMT", "msg": "HTTP Error 403: Forbidden", "server": "nginx", "status": 403, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://10.10.20.60/api/v1/sites", "x-ratelimit-limit": "-1", "x-ratelimit-remaining": "-1", "x-ratelimit-reset": "1559582945"}, "msg": "MSO Error:", "previous": {}, "raw": "", "status": 403}```
* ```"Referenced schema 'common_schema' in vrfref does not exist"```
* ```"Provided schema 'common_schema' does not exist."```

### Expected Behavior

* All the attached playbooks should work fine with a user who only has the schemaEditor role

### Actual Behavior

* They all fail.  They work fine when run as an admin user and it is also possible to do all these steps as the limited user through the web interface.

### Playbook tasks to Reproduce

I have attached some playbooks that will allow these issues to be reproduced.
[playbooks.zip](https://github.com/CiscoDevNet/ansible-mso/files/7837501/playbooks.zip)

Steps to reproduce.
1. Take a clean environment (for example: the Cisco DevNet Sandbox)
2. Run the setup-playbook.yml playbook using an admin account.  This will complete successfully and will set up the test environment for all the following tests.
3. Run any of the following playbooks as the limit user created by setup-playbook.yml (test_username):
   - playbook1.yml
   - playbook2.yml
   - playbook3.yml
   - playbook4.yml
   - playbook5.yml
   - playbook6.yml
   - playbook7.yml

These playbooks will all fail

**Comment by shrsr** [comment]
@paul759 Today the APIs consumed by our module mso_user are different from the ones used by UI which have their own dedicated APIs. In order to have a user with Schema editor privileges work on other modules, we suggest giving that user access to Read for Schema manger and Site manger. Please refer to the screen shot and let us know if you have any questions.

<img width="753" alt="Screen Shot 2022-01-28 at 17 59 30" src="https://user-images.githubusercontent.com/23535091/151864531-46122a98-0ace-4f57-a2dc-e071e98dd0d0.png">

**Comment by paul759** [comment]
Thanks @shrsr.  Can you clarify a couple of things for me.  

First of all, doesn't that mean that the test user can see details about every tenant?  The test user is supposed to represent a user from a given tenant that is trying to automate changes to their own tenant using ansible.  It doesn't seem appropriate to just give that tenant user access to every tenant (even read-only access) just so they can use ansible.  

Second of all, from what I can see in the swagger documenation (if you log into MSO and select API Docs), under the Schema API there are endpoints such as `/api/v1/schemas/allowed-sites` and `/api/v1/schemas/allowed-tenants` which would provide a lot of the name to ID lookups required by the ansible module.

**Comment by lhercot** [comment]
Hi @paul759, this issue is from MSO 3.0 and the schema editor role is not available in NDO which makes this issue irrelevant on new platforms.

We have tested your playbooks on NDO 3.7 and 4.1.1 and they run without an issue with the lowest level role available.

We will be closing this issue as "won't fix" as this require a large change in code behavior and only impact a small part of a soon to be end of life version.
