### ISSUE TITLE
mso_tenant : weird 404 error

### ISSUE THREAD

**Issue by RonaldBlom** [CiscoDevNet/ansible-mso#229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

mso_tenant module is returning a 404 error while querying a tenant. See error messsage.

### Affected Module Name(s):

* mso_tenant

### MSO version and MSO Platform

* V 3.5.2f and ND-based

### APIC version and APIC Platform for Site Level Resources

* V 4.2.6h and on-prem

### Collection versions

* cisco.mso 1.3.0

### Output/ Error message

* "msg": "MSO Error:",
    "raw": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n",
    "status": 404

### Expected Behavior

* query result for tenant should have been given

### Actual Behavior

* see error

### Playbook tasks to Reproduce

* TASK [aci.aci_change : Query to see if the ACI tenant exists and fail when absent] ****************************************************************************************************************************************************************
task path: /home/user/dev/Automation/ansible_collections/rabobank/aci/roles/aci_change/tasks/prechecks/input_validation_vlan_binding_to_epg_full_mso.yml:3
The full traceback is:
  File "/tmp/ansible_cisco.mso.mso_tenant_payload_5__2q32v/ansible_cisco.mso.mso_tenant_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py", line 591, in request
    payload = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
[DEPRECATION WARNING]: Distribution redhat 8.5 on host te--se99002 should use /usr/libexec/platform-python, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [host]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "current": {},
    "data": null,
    "info": {
        "body": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n",
        "connection": "close",
        "content-length": "153",
        "content-type": "text/html",
        "date": "Tue, 18 Jan 2022 12:49:16 GMT",
        "msg": "HTTP Error 404: Not Found",
        "server": "nginx/1.18.0",
        "status": 404,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://host/api/v1/users",
        "x-content-type-options": "nosniff",
        "x-ratelimit-limit": "0",
        "x-ratelimit-remaining": "0",
        "x-ratelimit-reset": "0",
        "x-xss-protection": "1; mode=block"
    },
    "invocation": {
        "module_args": {
            "description": null,
            "display_name": null,
            "host": "host",
            "login_domain": "Local",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "protocol": "https",
            "sites": null,
            "state": "query",
            "tenant": "tenant",
            "timeout": 30,
            "use_proxy": true,
            "use_ssl": true,
            "username": "user",
            "users": null,
            "validate_certs": false
        }
    },
    "msg": "MSO Error:",
    "raw": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n",
    "status": 404
}

### Important Factoids

no nothing
### References

* #0000

**Comment by mminnen** [comment]
👍

**Comment by mrpreve** [comment]
👍

**Comment by RonaldBlom** [comment]
This is the playbook/task:
- name: Query to see if the ACI tenant exists and fail when absent
  cisco.mso.mso_tenant:
    host: "{{ ansible_host }}"
    username: "{{ mso_username }}"
    password: "{{ mso_password }}"
    login_domain: "{{ mso_login_domain }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ tenant }}"
    state: query
  register: aci_tenant_query
  failed_when: aci_tenant_query.current == []

**Comment by shrsr** [comment]
@RonaldBlom 
1. Are you using the Nexus Dashboard (ND) connection plugin for this playbook? If not, please install the nd collection - `ansible-galaxy collection install cisco.nd` and set the following variables in your inventory file -
```
ansible_connection=ansible.netcommon.httpapi
ansible_network_os=cisco.nd.nd
```
2. Please use curly braces instead of brackets when using the failed_when conditional
failed_when: aci_tenant_query.current == {}

**Comment by RonaldBlom** [comment]
Hi, we just tried the above proposal. this is the result:

TASK [rabobank.aci.aci_change : Query to see if the ACI tenant exists and fail when absent] ******************************************************************************************************************************************************************
task path: /home/blomrp1.eu/dev/DCN%20Automation/ansible_collections/rabobank/aci/roles/aci_change/tasks/prechecks/input_validation_vlan_binding_to_epg_full_mso.yml:3
The full traceback is:
  File "/tmp/ansible_cisco.mso.mso_tenant_payload_x4_tmko4/ansible_cisco.mso.mso_tenant_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py", line 516, in request
    info = self.connection.send_request(method, uri, json.dumps(data))
  File "/tmp/ansible_cisco.mso.mso_tenant_payload_x4_tmko4/ansible_cisco.mso.mso_tenant_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[DEPRECATION WARNING]: Distribution redhat 8.5 on host te--se99002 should use /usr/libexec/platform-python, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [te--se99002]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "current": {},
    "invocation": {
        "module_args": {
            "description": null,
            "display_name": null,
            "host": "host",
            "login_domain": "Local",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "sites": null,
            "state": "query",
            "tenant": "tenant",
            "timeout": 30,
            "use_proxy": null,
            "use_ssl": null,
            "username": "user",
            "users": null,
            "validate_certs": false
        }
    },
    "msg": "Authentication failed: Request failed: command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}

Why do you think this should help by the way? All other tasks towards mso are working as expected.

**Comment by RonaldBlom** [comment]
Just added above to my inventory

fatal: [host]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "current": {},
    "data": null,
    "info": {
        "body": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n",
        "connection": "close",
        "content-length": "153",
        "content-type": "text/html",
        "date": "Thu, 03 Feb 2022 10:22:39 GMT",
        "msg": "HTTP Error 404: Not Found",
        "server": "nginx/1.18.0",
        "status": 404,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://host/api/v1/users",
        "x-content-type-options": "nosniff",
        "x-ratelimit-limit": "0",
        "x-ratelimit-remaining": "0",
        "x-ratelimit-reset": "0",
        "x-xss-protection": "1; mode=block"
    },
    "invocation": {
        "module_args": {
            "description": null,
            "display_name": null,
            "host": "host",
            "login_domain": "Local",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "protocol": "https",
            "sites": null,
            "state": "query",
            "tenant": "tenant",
            "timeout": 30,
            "use_proxy": true,
            "use_ssl": true,
            "username": "user",
            "users": null,
            "validate_certs": false
        }
    },
    "msg": "MSO Error:",
    "raw": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n",
    "status": 404
}

**Comment by RonaldBlom** [comment]
why I do get this with only this module? It looks you are suggesting a global (inventory) solution. But then I would expect this issue with all modules? Or do I not understand this correctly?

**Comment by RonaldBlom** [comment]
When having this in inventory:
mso_host_name ansible_host=mso_host_name ansible_httpapi_use_ssl=True ansible_connection=ansible.netcommon.httpapi ansible_network_os=cisco.nd.nd

I get following error:
The full traceback is:
  File "/tmp/ansible_cisco.mso.mso_tenant_payload_3xay7jzr/ansible_cisco.mso.mso_tenant_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py", line 516, in request
    info = self.connection.send_request(method, uri, json.dumps(data))
  File "/tmp/ansible_cisco.mso.mso_tenant_payload_3xay7jzr/ansible_cisco.mso.mso_tenant_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[DEPRECATION WARNING]: Distribution redhat 8.5 on host host should use /usr/libexec/platform-python, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [host]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "current": {},
    "invocation": {
        "module_args": {
            "description": null,
            "display_name": null,
            "host": "host",
            "login_domain": "Local",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "sites": null,
            "state": "query",
            "tenant": "tenant",
            "timeout": 30,
            "use_proxy": null,
            "use_ssl": null,
            "username": "user",
            "users": null,
            "validate_certs": false
        }
    },
    "msg": "Authentication failed: Request failed: maximum recursion depth exceeded while calling a Python object"
}

**Comment by mminnen** [comment]
Have tested this with the following tasks.

- The task seems to work when the login_domain is NOT explicitely set (so, it defaults to "Local). 
- If the first tasks in the playbook sets the login_domain to "Local" , a timeout occurs.

=========================

  - name: First task (works)
    cisco.mso.mso_tenant:
      host: "{{ ansible_host }}"
      username: "{{ mso_username }}"
      password: "{{ mso_password }}"
      # login_domain: "{{ mso_login_domain }}"  # The login domain is not set explicitely
      validate_certs: "no"
      tenant: "test"
      state: query
    vars:
      - ansible_connection: ansible.netcommon.httpapi
      - ansible_network_os: cisco.nd.nd
      - ansible_httpapi_use_ssl: True

 - name: First task (fails)
    cisco.mso.mso_tenant:
      host: "{{ ansible_host }}"
      username: "{{ mso_username }}"
      password: "{{ mso_password }}"
      login_domain: "Local"  # If this is set the task/module fails, it has to be set on the first task
      validate_certs: "no"
      tenant: "test"
      state: query
    vars:
      - ansible_connection: ansible.netcommon.httpapi
      - ansible_network_os: cisco.nd.nd
      - ansible_httpapi_use_ssl: True

**Comment by RonaldBlom** [comment]
[Cisco_devnet.zip](https://github.com/CiscoDevNet/ansible-mso/files/8108877/Cisco_devnet.zip)

Attached, you find the playbook and files we tested with.

**Comment by RonaldBlom** [comment]
Hi, we added these four variables to our mso.yml in group_vars and it is working for this mso_tenant module.
ansible_connection: ansible.netcommon.httpapi
ansible_network_os: cisco.nd.nd
ansible_httpapi_use_ssl: True
mso_login_domain: "TACACS"

But now a lot of things which were working before are not working anymore as expected.

For example on cisco.mso.mso_schema we are doing a query on specific schema.
This is failing now with following error:
nsible.module_utils.connection.ConnectionError: Unable to decode JSON from response set_options. See the debug log for more information

So I added "delegate_to: localhost", but now I got following error:
"msg": "MSO Error:", 
    "payload": {
        "error": "Invalid parameters.", 
        "statusCode": 500
    }, 
    "status": 500

**Comment by lonibble** [comment]
I receive the same 404 error when trying to query or create the tenant. My playbook works just fine on MSO 3.1.1.  I am upgrading to 3.7.1d and this issue appeared.  If I manually create the tenant and skip this task in my playbook everything else works from creating a schema, BDs, EPGs, VRFs, etc. and all the associations just fine.  I have all the above variables and still get the same results.

**Comment by akinross** [comment]
closing due to unreproducible issue
