### ISSUE TITLE
Creating a BD subnet under a site should create the BD under the site if it does not exist

### ISSUE THREAD

**Issue by adealdag** [CiscoDevNet/ansible-mso#237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, in scenarios where we want to create a Bridge Domain under a given template, but the subnet is configured under the site (i.e. for non-l2-stretched bds) we have to use the module `mso_schema_site_bd` to create the BD under the site, even if we don't need to modify any property of that object. If we don't do that, `mso_schema_site_bd_subnet` module fails.

The enhancement request is for the `mso_schema_template_bd` module to create `mso_schema_site_bd` as well, simplifying operations and providing a process more similar to what users are used to in the UI.

Alternatively, if creating `mso_schema_site_bd` is a scalability concern, the object can be created when creating the subnet using `mso_schema_site_bd_subnet` if the template BD exists but not the site BD.

One last alternative could be to provide the option to create the subnet and l3out association under the module `mso_schema_site_bd` directly, similarly to what's possible on the template BD.

### New or Affected Module(s):

* mso_schema_template_bd
* mso_schema_site_bd
* mso_schema_site_bd_subnet

### MSO version and MSO Platform

* V 3.6.1e on vND 2.1.2d

### Collection versions

* cisco.mso 1.3.0

### References

* #0000

**Comment by lhercot** [comment]
We cannot add the site level construct when doing the template level change as we don't know how many sites are there and they might not have been added to the template yet.

We can try adding the creation of the BD object when it does not exist when you configure a subnet under it.
