### ISSUE TITLE
backup and restore module 

### ISSUE THREAD

**Issue by rtrentin73** [CiscoDevNet/ansible-mso#24]

**Comment by lhercot** [comment]
@rtrentin73 , can you add a bit of details on what is the use case for the Backup / Restore modules?

What operation are you trying to automate?

**Comment by lhercot** [comment]
Part of this request is fixed with PR #80 more specifically creating, querying and deleting local and remote backups.
I will open other issues to track the missing part of the request (restore, download, upload, move to remote).
