### ISSUE TITLE
Create a bulk version of mso_schema_site_anp_epg_staticport to handle multiple bindings at once to speed up operations

### ISSUE THREAD

**Issue by lhercot** [CiscoDevNet/ansible-mso#297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

cisco.mso.mso_schema_site_anp_epg_staticport handles the static path binding to NDO.
Customers can have 100's or 1000's of bindings and executing the individual module can be slow.
We should add a new module that allow the configuration of all bindings for a specific EPG in the same PATCH request (similar to aci_bulk_epg_to_static_path).

### New or Affected Module(s):

* mso_schema_site_anp_epg_bulk_staticport

### MSO version and MSO Platform

* all.

### APIC version and APIC Platform for Site Level Resources

* on-prem

**Comment by chumhub** [comment]
@lhercot - Do you have any suggested workarounds until this could be delivered? Aside from slowness, the current module will timeout once the MSO/NDO authentication token expires (20 minutes, by default?), and it does not appear to attempt to retrieve a refreshed token.
