### ISSUE TITLE
MSO - Add more filters to contract

### ISSUE THREAD

**Issue by mupett** [CiscoDevNet/ansible-mso#298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* xxxx

### New or Affected Module(s):

* mso_XXXXX
* cisco.mso.mso_schema_template_contract_filter module

### MSO version and MSO Platform

* V x.x.x and Docker Swarm OVA-based/SE-based/ND-based/all.
* Version: 3.7(1l)

### APIC version and APIC Platform for Site Level Resources

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Collection versions

* cisco.mso x.x.x
cisco.mso         2.1.0  
cisco.nd          0.1.2
### References

* #0000

**Comment by lhercot** [comment]
Hi @mupett , could you elaborate on what your enhancement request is about?

Are you trying to add more filters to the same contract?
If so, you can just use the "mso_schema_template_contract_filter" module multiple times on the same contract to add more elements to it.

**Comment by mupett** [comment]
Hello Lionel,
I'm not able to make it work.
When I try to add an FLT_SSH to the existing CTR_victoria contract, I got the output below.

Kind Regards
Luca



failed: [co005cnm.networkla.fw] (item={'schema': 'SCH_pdd.aws-rbm-nopro', 'template': 'TEMPL_aws-cloud', 'ctr': 'CTR_victoria', 'scope': 'global', 'filter': 'FLT_SSH', 'filter_type': 'both-way', 'directive': 'none'}) => {
    "ansible_loop_var": "tenantctrs_list",
    "changed": true,
    "current": {
        "contractFilterType": "bothWay",
        "contractScope": "global",
        "description": "",
        "directives": [
            "none"
        ],
        "displayName": "CTR_victoria",
        "filterRef": {
            "filterName": "FLT_SSH",
            "schemaId": "6373684d210000d5437fd227",
            "templateName": "TEMPL_aws-cloud"
        },
        "filterType": "both-way",
        "prio": "unspecified"
    },
    "data": [
        {
            "op": "replace",
            "path": "/templates/TEMPL_awsCTR_victoriacloud/contracts/CTR_victoria/scope",
            "value": "global"
        },
        {
            "op": "replace",
            "path": "/templates/TEMPL_awsCTR_victoriacloud/contracts/CTR_victoria/filterType",
            "value": "bothWay"
        },
        {
            "op": "add",
            "path": "/templates/TEMPL_aws-cloud/contracts/CTR_victoria/filterRelationships/-",
            "value": {
                "contractFilterType": "bothWay",
                "contractScope": "global",
                "description": "",
                "directives": [
                    "none"
                ],
                "displayName": "CTR_victoria",
                "filterRef": {
                    "filterName": "FLT_SSH",
                    "schemaId": "6373684d210000d5437fd227",
                    "templateName": "TEMPL_aws-cloud"
                },
                "filterType": "both-way",
                "prio": "unspecified"
            }
        }
    ],
    "info": {
        "body": {
            "code": 141,
            "message": "Resource Not Found: template with name TEMPL_awsCTR_victoriacloud not found in List(TEMPL_aws-cloud)"
        },
        "connection": "close",
        "content-language": "en",
        "content-length": "125",
        "content-type": "application/json",
        "error": {
            "code": -1,
            "message": {
                "code": 141,
                "message": "Resource Not Found: template with name TEMPL_awsCTR_victoriacloud not found in List(TEMPL_aws-cloud)"
            }
        },
        "method": "PATCH",
        "msg": "OK (125 bytes)",
        "server": "nginx",
        "status": 400,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://co005cnm.networkla.fw:443/mso/api/v1/schemas/6373684d210000d5437fd227?validate=false",
        "x-ratelimit-limit": "-1",
        "x-ratelimit-remaining": "-1",
        "x-ratelimit-reset": "1559582945"
    },
    "invocation": {
        "module_args": {
            "action": null,
            "contract": "CTR_victoria",
            "contract_display_name": null,
            "contract_filter_type": "both-way",
            "contract_scope": "global",
            "description": null,
            "filter": "FLT_SSH",
            "filter_directives": [
                "none"
            ],
            "filter_schema": "SCH_pdd.aws-rbm-nopro",
            "filter_template": "TEMPL_aws-cloud",
            "filter_type": "both-way",
            "host": "co005cnm.networkla.fw",
            "login_domain": null,
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "priority": null,
            "qos_level": null,
            "schema": "SCH_pdd.aws-rbm-nopro",
            "state": "present",
            "template": "TEMPL_aws-cloud",
            "timeout": 30,
            "use_proxy": null,
            "use_ssl": null,
            "username": "ansible",
            "validate_certs": false
        }
    },
    "msg": "MSO Error 141: Resource Not Found: template with name TEMPL_awsCTR_victoriacloud not found in List(TEMPL_aws-cloud)",
    "payload": {
        "code": 141,
        "message": "Resource Not Found: template with name TEMPL_awsCTR_victoriacloud not found in List(TEMPL_aws-cloud)"
    },
    "status": 400,
    "tenantctrs_list": {
        "ctr": "CTR_victoria",
        "directive": "none",
        "filter": "FLT_SSH",
        "filter_type": "both-way",
        "schema": "SCH_pdd.aws-rbm-nopro",
        "scope": "global",
        "template": "TEMPL_aws-cloud"
    }
}

**Comment by akinross** [comment]
Hi @mupett,

I think this is a bug in our code when - is used in the "filter_template": "TEMPL_aws-cloud". In the code a replace is done for the "-" character which replaces all "-" in a string. Thus "/templates/TEMPL_awsCTR_victoriacloud/contracts/CTR_victoria/scope" is created instead of "/templates/TEMPL_aws-cloud/contracts/CTR_victoria/scope". 

Could you validate if the behaviour is also present without "-" in your naming?

Kind regards,

**Comment by mupett** [comment]
Hello, I'll check it and let you know. Thanks and regards.

**Comment by mupett** [comment]
Hello,
It still doesn'work.
I removed "-" from schema, template, filters and contract definitions but I still have and error:

failed: [myhost] (item={'schema': 'SCH_pdd.awsnopro2', 'template': 'TEMPL_awscloud', 'ctr': 'CTR_internetawsHTTPSinbound', 'scope': 'vrf', 'filter': 'FLT_ICMP', 'filter_type': 'both-way', 'directive': 'none'}) => {"ansible_loop_var": "tenantctrs_list", "changed": true, "current": {"contractFilterType": "bothWay", "contractScope": "context", "directives": ["none"], "displayName": "CTR_internetawsHTTPSinbound", "filterRef": {"filterName": "FLT_ICMP", "schemaId": "638db54b3232b20430437e91", "templateName": "TEMPL_awscloud"}, "filterType": "both-way"}, "data": [{"op": "add", "path": "/templates/TEMPL_awscloud/contracts/-", "value": {"displayName": "CTR_internetawsHTTPSinbound", "filterType": "bothWay", "name": "CTR_internetawsHTTPSinbound", "scope": "context"}}, {"op": "add", "path": "/templates/TEMPL_awscloud/contracts/CTR_internetawsHTTPSinbound/filterRelationships/-", "value": {"contractFilterType": "bothWay", "contractScope": "context", "directives": ["none"], "displayName": "CTR_internetawsHTTPSinbound", "filterRef": {"filterName": "FLT_ICMP", "schemaId": "638db54b3232b20430437e91", "templateName": "TEMPL_awscloud"}, "filterType": "both-way"}}], "info": {"body": {"code": 400, "message": "add operation does not apply: doc is missing path: \"/templates/0/contracts/0/filterRelationships/-\": missing value"}, "connection": "close", "content-language": "en", "content-length": "141", "content-type": "application/json", "error": {"code": -1, "message": {"code": 400, "message": "add operation does not apply: doc is missing path: \"/templates/0/contracts/0/filterRelationships/-\": missing value"}}, "method": "PATCH", "msg": "OK (141 bytes)", "server": "nginx", "status": 400, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://myhost:443/mso/api/v1/schemas/638db54b3232b20430437e91?validate=false", "x-ratelimit-limit": "-1", "x-ratelimit-remaining": "-1", "x-ratelimit-reset": "1559582945"}, "msg": "MSO Error 400: add operation does not apply: doc is missing path: \"/templates/0/contracts/0/filterRelationships/-\": missing value", "payload": {"code": 400, "message": "add operation does not apply: doc is missing path: \"/templates/0/contracts/0/filterRelationships/-\": missing value"}, "status": 400, "tenantctrs_list": {"ctr": "CTR_internetawsHTTPSinbound", "directive": "none", "filter": "FLT_ICMP", "filter_type": "both-way", "schema": "SCH_pdd.awsnopro2", "scope": "vrf", "template": "TEMPL_awscloud"}}

**Comment by akinross** [comment]
HI @mupett,

Which version of NDO are you using?

**Comment by mupett** [comment]
4.0

**Comment by akinross** [comment]
Hi @mupett,

I have made previous remark in other issue regarding the current use of NDO 4.0 (#300) in combination with the ansible collection. We are aware that multiple modules are not working anymore for NDO4.0. Changes have been made to the NDO4.0 API which are impacting the collection. We are currently working on fixes to address these issues.

**Comment by mupett** [comment]
Hello thanks.
Can I use the fixed software by reinstalling the collection? Or I have to wait for the new release?

Regards
Luca
