### ISSUE TITLE
mso_schema_template_deploy doesn't work

### ISSUE THREAD

**Issue by angelogemma** [CiscoDevNet/ansible-mso#299]
Hi Team,
I have some issue with the module used to deploy a template on MSO Servicie of Nexus Dashboard Orchestrator Version 2.2(2d).

This is the excerpt of the ansible playbook:
    - name: DEPLOY DEL TEMPLATE
      cisco.mso.mso_schema_template_deploy:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        schema: "SCHEMA1"
        template: "TEMP1"
        state: deploy

This is the returned error from ansible:
`TASK [DEPLOY DEL TEMPLATE] *******************************************************************************************************************************************************************
fatal: [10.10.20.60]: FAILED! => {"changed": false, "current": {}, "msg": "Connection failed for https://10.10.20.60:443/mso/api/v1/execute/schema/637270235aa848e4be8e6901/template/TEMP1. OK (19 bytes)", "status": 404}`

When I deploy a template from a python script I use the following and it works.

POST : https://10.10.20.60:443/mso/api/v1/task
Body: {"schemaId":"6372296221ecac1dc5370ce1","templateName":"TEMP4","isRedeploy":true,"_updateVersion":0}

Please can you check?
Thank you in advance.

**Comment by akinross** [comment]
Hi @angelogemma, I think you provided the Nexus Dashboard version, what version of NDO are you currently running?

**Comment by angelogemma** [comment]
Yes @akinross , you are right. Sorry. The MSO version is 4.0.2i.
I was using the sandbox provided by Cisco DevNet.
Thank you very much!
Angelo

**Comment by akinross** [comment]
Hi @angelogemma, the api endpoint for deploy has changed in NDO4.0 so this module will only provide the functionality for NDO versions before 4.0. We are working on implementing a new module for this new api endpoint.

**Comment by angelogemma** [comment]
Thank you @akinross .
Have a good day.

**Comment by angelogemma** [comment]
In the meantime, if someone needs a workaround, in this way it works:
    - name: FIND SCHEMA ID
      cisco.mso.mso_schema:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        schema: "{{ schema }}"
        state: "query"
      register: schemaID

    - name: DEPLOY TEMPLATE
      cisco.mso.mso_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        path: /mso/api/v1/task
        method: post
        content:
          {
            "schemaId":"{{ schemaID.current.id }}",
            "templateName":"{{ template }}",
            "isRedeploy":true,
            "_updateVersion":0
          }
