### ISSUE TITLE
cisco.mso.mso_schema - could not create remote user

### ISSUE THREAD

**Issue by RonaldBlom** [CiscoDevNet/ansible-mso#310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* After upgrading NDO to 3.7.2d, we get this error from the mso_schema module: could not create remote user

### Affected Module Name(s):

* mso_schema

### MSO version and MSO Platform

* V 3.7.2d and ND-based

### APIC version and APIC Platform for Site Level Resources

* V 5.2.5c and on-prem

### Collection versions

* cisco.mso 1.4.0

### Output/ Error message

*

### Expected Behavior

* query all schema's and register as result

### Actual Behavior

* fails with error: could not create remote user

### Playbook tasks to Reproduce

* - name: "Get all MSO schemas"
  cisco.mso.mso_schema:
    host: "{{ ansible_host }}"
    username: "{{ mso_username }}"
    password: "{{ mso_password }}"
    login_domain: "{{ mso_login_domain }}"
    validate_certs: "{{ validate_certs }}"
    state: query
  register: aci_netcentric_mso_schemas_query_all

### References

* #0000

**Comment by akinross** [comment]
Hi @RonaldBlom ,

I have just tested on 3.7.2d and not getting this error, are you sure it is coming from the mso_schema module? Did you execute this isolated or as part of larger code base?

Kind regards,

Akini

**Comment by RonaldBlom** [comment]
Hi Akini,

Sorry, but this is solved by itself. In week after upgrade we got the error several times, not always, which was strange because automation is using same functional account/user. And then it was solved suddenly. I did not change anything.

So I will close this issue.

Thank you for your response!

Regards,
Ronald
