### ISSUE TITLE
Module Missing: Schema > Template > Site > Contracts > Service Graph > Select Cluster Interfaces and Redirect Policy

### ISSUE THREAD

**Issue by metalhead4711** [CiscoDevNet/ansible-mso#329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If we configure a Service Graph via NDO we have the 4 following steps:
- Create Service Graph in Schema > Template (Ansible Module in Version 2.2.1 mso_schema_template_service_graph)
- Create a contract and bind the service graph in Schema > Template (Ansible Module in Version 2.2.1 mso_schema_template_contract_service_graph)
- Select L47 Device in Schema > Template > Site > Service Graph (Ansible Module in Version 2.2.1 mso_schema_site_service_graph_node)
- Select Cluster Interfaces in Schema > Template > Site > Contract > Service Graph > No module available. Without such a module the 3 other modules do not make any sence.

### Affected Module Name(s):

Module missing, See desciption above

### MSO version and MSO Platform

* all.

### APIC version and APIC Platform for Site Level Resources

* all.

### Collection versions

* cisco.mso 2.2.1

### Output/ Error message

* no Error, because Module is completely missing

### Expected Behavior

*
Module available for the last config step

### Actual Behavior

*
Module missing

### Playbook tasks to Reproduce

*

Module Missing, so no playbook

### References

* #0000

**Comment by akinross** [comment]
Hi @metalhead4711,

There is currently already an issue tracking this #275 which has a PR #281 that I am currently working on. Please follow the PR and issue just provided for any updates. I will proceed with closure of this issue.
