### ISSUE TITLE
Unable to add same path to different leafs when adding static ports in bulk

### ISSUE THREAD

**Issue by sacascio** [CiscoDevNet/ansible-mso#357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When adding static ports in bulk, unable to add the same path to different leaf switches on the same EPG

### Affected Module Name(s):

mso_schema_site_anp_epg_bulk_staticport

### MSO version and MSO Platform

NDO Version V 3.7(1L), ND based.
ND Version: 2.2(1h)

### APIC version and APIC Platform for Site Level Resources

APIC on Prem, version 5.2(3g)

### Collection versions

cisco-mso-2.3.0

### Output/ Error message

TASK [Add bulk static ports for EPG VDI_EPG_20] *******************************************************************************
fatal: [host1 -> localhost]: FAILED! => {"changed": true, "current": {"deploymentImmediacy": "immediate", "mode": "untagged", "path": "topology/1/paths-2773/pathep-[eth1/1]", "portEncapVlan": 20, "type": "port"}, "msg": "Path should be unique for each Static Port"}

### Expected Behavior

ok: [host1 -> localhost]

PLAY RECAP *******************************************************************************************************************
host1                      : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

### Actual Behavior

ansible task failed and did not create any static ports on the EPG

### Playbook tasks to Reproduce

      type: port
      leaf: 2772
      path: eth1/1
      vlan: 20
      pod: 1
      deployment_immediacy: immediate
      static_ports:
        - leaf: 2773
          path: eth1/1
          vlan: 20
        - leaf: 2774
          path: eth1/1
          vlan: 20

### Important Factoids

Changing the second static port in the snippet above from leaf: 2774, path: eth1/1 to path: eth1/2 produces no error and works without failure.

### References

None

**Comment by lhercot** [comment]
Thanks for opening the bug. We will be looking at it soon.

Just FYI, you do not have to repeat the vlan per static_ports if you define it at the module level.
The same way, you would probably not define path or leaf at the module level if you are overriding it in every list item.
