### ISSUE TITLE
Incremental static port add to EPG in bulk

### ISSUE THREAD

**Issue by sacascio** [CiscoDevNet/ansible-mso#376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently there is an ansible module to add static ports to EPG in bulk.  Looking to enhance that module to add additional static ports in bulk (incremental add)

Enhance static port add in bulk to add incremental static ports in bulk without deleting existing static ports configured

### New or Affected Module(s):

* mso_schema_site_anp_epg_bulk_staticport

### MSO version and MSO Platform

* V3.7.1(l) NDO
* 2.2.1(h) Nexus Dashboards (Virtual)

### APIC version and APIC Platform for Site Level Resources

* V 5.2(7g)

### Collection versions

* cisco.mso 2.4.0

### References

* #0000

**Comment by PC12360** [comment]
That will be a great enhancement !!!
