### ISSUE TITLE
Unable to set schema and template for L3out in mso_schema_site_external_epg

### ISSUE THREAD

**Issue by mnejedlo-tds** [CiscoDevNet/ansible-mso#383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* While attempting to use mso_schema_site_external_epg, I ran into a problem where the l3out parameter assumes the same schema and template name as for the eEPG, but having the eEPG and L3out in different schemas/templates is an allowed configuration in NDO.  Please update mso_schema_site_external_epg to use a name/schema/template dictionary for the l3out parameter, similar to how mso_schema_template_external_epg works currently.

### New or Affected Module(s):

* mso_schema_site_external_epg

### MSO version and MSO Platform

* V 3.6.1e on ND 2.1(2d) (VMware/OVA based)

### APIC version and APIC Platform for Site Level Resources

* V 5.2(3g) on-prem

### Collection versions

* cisco.mso 2.5.0

**Comment by shrsr** [comment]
@mnejedlo-tds Thank you for opening the issue. Our team will look into it and come up with a solution.
