### ISSUE TITLE
MSO Error 500: The token is expired since 2023-11-03T12:04:05Z

### ISSUE THREAD

**Issue by phil-dotchon** [CiscoDevNet/ansible-mso#385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* We have a large and complex playbook that (in this case) constructs application centric environments using ansible-mso and ansible-aci  amongst others. Our plays can take a long time to complete and a recent application appears to have pushed this to a point where the mso API authentication token requested by ansible-mso is expiring. I am assuming that the httpapi code is not keeping track of the lifetime of a token and is not refreshing the token when it reaches a certain age. I don't see any option for choosing the token refresh time. Admittedly we are not running the current release of ansible-mso, but I don't see any mention of this being addressed in later versions.

Is there a way to trigger re-authentication or token refresh at some point in a play?

We have experimented with altering the session timeout in NDO, but this is not really ideal and will be difficult to justify/deploy in a production environment. Making the ND timeout longer does appear to solve the problem, but we don't consider this to be a true resolution

### Affected Module Name(s):

* probably any of them

### MSO version and MSO Platform

* NDO version 3.7(1j)  ND version 2.1(1e) ND-based

### APIC version and APIC Platform for Site Level Resources

* V 5.2(4d) on-prem

### Collection versions

* cisco.mso 2.2.1 

### Output/ Error message

* MSO Error 500: The token is expired since 2023-11-03T12:04:05Z

### Expected Behavior

* The timeout should not occur, the ansible modules should refresh the token before it expires

### Actual Behavior

* After the play has been running for 20 minutes or longer we see a fatal failure roughly in the same point in the play, where MSO is responding with an error due to the ansible module trying to use an expired authentication token

### Playbook tasks to Reproduce

* A long play that runs beyond the configured NDO session timeout

### References

* https://developer.cisco.com/docs/nexus-dashboard/latest/#!getting-started/authorization-using-user-credentials-and-api-token

**Comment by lhercot** [comment]
Hi @phil-dotchon, what is the version of NDO you are running? You mentioned you are running on ND v2.1(1e) but you didn't share the NDO version.

Also does it always fail on a specific task or randomly on a series?

**Comment by phil-dotchon** [comment]
Ah sorry, we are running NDO version 3.7(1j) , on top of ND version 2.1(1e).
I'm not sure if it was always the same task, I could test that, but I can say that since I updated the ND session timeout under security configuration, from 20 minutes to 60 minutes the problem hasn't appeared.

**Comment by akinross** [comment]
HI @phil-dotchon, could you provide me some additional information regarding your ansible version, ansible.netcommon, and the ansible-nd collection version?

**Comment by akinross** [comment]
HI @phil-dotchon, ok no worries have parked it in waiting for info. As soon as you provided me additional information will have a look.

**Comment by phil-dotchon** [comment]
> Hi @phil-dotchon,
> 
> If you could set output level to debug and verbosity level higher on your playbook execution. Could your try it a couple of times to also see the difference in the modules on which it fails.
> 
> Furthermore is there a reason for not running later releases of netcommon, nd?

Hi @akinross , forgive me but can you expand on what you mean by 'set output level to debug'? As far as I'm aware there is no 'debug' output in ansible-playbook?

**Comment by phil-dotchon** [comment]
OK I see; I'm running now with debug and -vvv. For info, here is what I got with the NDO session timeout back at 20 mins without changing the `output_level ` and with -vvv. This shows the last successful iteration of the loop, then the failed iteration and retries. It may be that with the `output_level` being different the timing will also mean the failure happens somewhere else, but lets see...
[mso-timeout-run1-vvv.txt](https://github.com/CiscoDevNet/ansible-mso/files/13634712/mso-timeout-run1-vvv.txt)

**Comment by akinross** [comment]
Hi @phil-dotchon, thank you for sharing. I will have a look at it and get back to you.

**Comment by akinross** [comment]
Hi @phil-dotchon, 

I have not been able to reproduce the issue in my ansible setup yet. I would need to create a large enough playbook and get "lucky" to hit it. I would need to reproduce it in a ansible playbook in order to test a potential fix.

I have been able to reproduce the issue by sending requests manually. Where I can send any request with AuthCookie containing the correct token and Bearer token containing a "expired" token. In this scenario the expired token seems to be checked by some internal service and returning a status 500. This is also why the re-authentication mechanism that is currently in place is not triggered, since that requires a 401 status code.

It appears to be only triggered in 3.7 releases of NDO, and not in 4.1 or 4.2 releases of NDO. You are currently still on old version of NDO, are you planning to upgrade any time soon?

**Comment by phil-dotchon** [comment]
Hi @akinross, yes I understand it's difficult to reproduce; I'm not aware of any plan to upgrade in the short term, though I'm sure we will come to that eventually. At the moment we have viable workaround, by increasing the session time-out, and I'll raise this issue internally as a factor encouraging us to update sooner rather than later. It's good you have an understanding of the problem and that it apparently doesn't exist in later releases, so I'm happy to close this issue on that basis. Thanks for looking into this for us.
