### ISSUE TITLE
Contract relationships bulk module

### ISSUE THREAD

**Issue by pcelarek** [CiscoDevNet/ansible-mso#406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Deploying a lot of consumer/provider contract relationships using current cisco.mso.mso_schema_template_anp_epg_contract module can be very slow and cause timeouts. 
It would be really nice to have contract bulk module, similar to static one mso_schema_site_anp_epg_bulk_staticport 
### New or Affected Module(s):

mso_schema_template_anp_epg_**bulk**_contract module

### MSO version and MSO Platform

Starting from NDO 3.7

**Comment by akinross** [comment]
Hi @pcelarek, I have added the item to the todo list. Could you provided a bit more details on the amount of contracts?

**Comment by pcelarek** [comment]
> Hi @pcelarek, I have added the item to the todo list. Could you provided a bit more details on the amount of contracts?

Hello Akini, just to clarify not the amount of contracts is an issue - usually this part we can manage, the biggest issue is with contract association (consumer/provider part). 
For example based on may lab testing 500 contract rules like that will take around 50 minutes, 900 lines close to 2h and when schema is growing it could be even slower. In most of the deployments we can manage this better with use of vZany, but sometimes this is not possible when more granular approach is required.
So to answer your question I am asking about hundreds of consumer/provider rules in one push.

**Comment by akinross** [comment]
Hi @pcelarek, thanks for the clarification.
