### ISSUE TITLE
LDAP Authentication fails

### ISSUE THREAD

**Issue by mwielpue2** [CiscoDevNet/ansible-mso#407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are trying to use LDAP authentication. For this we use the MSO_LOGIN_DOMAIN.
The code expects ND to reply with JSON content, but we receive HTML. This leads to a failure in parsing the JSON. See stack trace below

### Affected Module Name(s):

* module_utils/mso.py

### MSO version and MSO Platform

* ND 2.3.2d and NDO 3.7.2g 

### APIC version and APIC Platform for Site Level Resources

* APIC 6.0.3

### Collection versions

* cisco.mso 2.2.1

### Output/ Error message

TypeError: 'NoneType' object is not iterable
fatal: [MSO]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File
\"/home/e0086253/.ansible/tmp/ansible-tmp-1707928872.5668402-251388-140361338684605/AnsiballZ_mso_rest.py
\", line 107, in <module>\n    _ansiballz_main()\n  File
\"/home/e0086253/.ansible/tmp/ansible-tmp-1707928872.5668402-251388-140361338684605/AnsiballZ_mso_rest.py
\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path,
ANSIBALLZ_PARAMS)\n  File
\"/home/e0086253/.ansible/tmp/ansible-tmp-1707928872.5668402-251388-140361338684605/AnsiballZ_mso_rest.py
\", line 47, in invoke_module\n
runpy.run_module(mod_name='ansible_collections.cisco.aac.plugins.modules.mso_rest',

init_globals=dict(_module_fqn='ansible_collections.cisco.aac.plugins.modules.mso_rest',
 _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in
run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File
\"<frozen runpy>\", line 88, in _run_code\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/aac/plugins/modules/mso_rest.py
\", line 241, in <module>\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/aac/plugins/modules/mso_rest.py
\", line 132, in main\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py
\", line 355, in __init__\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py
\", line 383, in login\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py
\", line 371, in get_login_domain_id\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py
\", line 782, in get_obj\n  File
\"/tmp/ansible_cisco.aac.mso_rest_payload_l_lfgr1t/ansible_cisco.aac.mso_rest_payload.zip/ansible_collections/cisco/mso/plugins/module_utils/mso.py
\", line 739, in query_objs\nTypeError: 'NoneType' object is not iterable
\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

### Expected Behavior

* LDAP authentication should have worked.

**Comment by akinross** [comment]
The http api connection plugin from ansible-nd was not properly used, assistend in putting the correct settings in inventory and then problem was resolved.

```
ansible_connection=ansible.netcommon.httpapi
ansible_network_os=cisco.nd.nd
ansible_httpapi_login_domain=<SOME DOMAIN>
```

**Comment by mwielpue2** [comment]
Thanks for your support @akinross!

One remark:
I think it would be worth to adapt the README.md to make it more specific on where to put the plugin configs.
