### ISSUE TITLE
Items for 0.0.6 to work in MSO pipeline

### ISSUE THREAD

**Issue by tkuik** [CiscoDevNet/ansible-mso#58]
Various items needed to resolve pipeline integration.

Allow apic_site_id to be passed: Perhaps `'{{ apic_id }}’`
- tests/integration/targets/mso_schema_site_anp_epg_domain/tasks/main.yml

Not using passed mso_username:
- tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml line 43
- tests/integration/targets/mso_schema_template_anp_epg_contract/tasks/main.yml line 43
- tests/integration/targets/mso_tenant/tasks/main.yml line 203
- tests/integration/targets/mso_schema_template_bd/tasks/main.yml line 43
- tests/integration/targets/mso_schema_template_contract_filter/tasks/main.yml line 44
- tests/integration/targets/mso_schema_template_external_epg_contract/tasks/main.yml line 43

**Comment by Rahul-Cisco-MSO** [comment]
- ./mso_tenant/tasks/main.yml - line 171 - remove `- admin`

Change below to pass `apic_id` as parameter
- ./mso_schema_template_external_epg_contract/tasks/main.yml:27:#     apic_site_id: '{{ apic_id }}'
- ./mso_schema_template_contract_filter/tasks/main.yml:28:#     apic_site_id: '{{ apic_id }}'
- ./mso_schema_template_bd/tasks/main.yml:27:    apic_site_id: '{{ apic_id }}'
- ./mso_site/tasks/main.yml:119:    apic_site_id: '{{ apic_id }}'
- ./mso_site/tasks/main.yml:432:    apic_site_id: '{{ apic_id }}'
- ./mso_schema_template_anp_epg_contract/tasks/main.yml:27:#     apic_site_id: '{{ apic_id }}'
- ./mso_schema_template_anp_epg/tasks/main.yml:27:#     apic_site_id: '{{ apic_id }}'
- ./mso_schema_site_anp_epg_domain/tasks/main.yml:31:    apic_site_id: '{{ apic_id }}'

**Comment by Rahul-Cisco-MSO** [comment]
tests/integration/targets/mso_tenant/tasks/main.yml file on line 180, 196 and 248 change the == 2 to == 1
This is due to the use of admin as user for the tests. Need to find a better way to check this condition in the test, as per Lionel.

**Comment by Rahul-Cisco-MSO** [comment]
./mso_tenant/tasks/main.yml -  had to make below changes for it to pass
```
    212     - nm_add_tenant3_with_duplicate_admin is changed
    213 #    - nm_add_tenant3_with_duplicate_admin.msg == "User 'admin' is duplicate."

    245     - nm_add_tenant3 is not changed
