### ISSUE TITLE
[mso_schema_template_anp_epg] AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ysolan** [CiscoDevNet/ansible-mso#66]
Module Failure when using state [query, present]

AttributeError: 'NoneType' object has no attribute 'group'

[mso_schema_template_anp_epg.error.txt](https://github.com/CiscoDevNet/ansible-mso/files/4845788/mso_schema_template_anp_epg.error.txt)

**Comment by lhercot** [comment]
Hi @ysolan which version of the collection do you use?
Can you share an example playbook which trigger this issue?

**Comment by ysolan** [comment]
Hi @lhercot 
i use collection v0.0.6
Here an example of our schema and task query.
[mso_issue_66_schema.txt](https://github.com/CiscoDevNet/ansible-mso/files/4851389/mso_issue_66_schema.txt)
[mso_issue_66_task.txt](https://github.com/CiscoDevNet/ansible-mso/files/4851390/mso_issue_66_task.txt)

**Comment by lhercot** [comment]
v0.0.7 of the collection will have a fix for this condition. Should be out soon.

**Comment by ysolan** [comment]
Hello,

Still issue with collection v.0.0.7 with same error message.
