### ISSUE TITLE
[mso_backup] Add missing actions to backup module

### ISSUE THREAD

**Issue by lhercot** [CiscoDevNet/ansible-mso#84]
mso_backup allows the creation, querying and deletion of backups locally or remotely.
This enhancement is to extend those capabilities with the following actions:
- import (upload) from remote location and from file.
- Rollback to a backup
- download to local file
- move backup from local to remote

**Comment by oraclek76** [comment]
This goes along with the other backup module.  Either or both would be great.  One of my customers is asking for this.
