### ISSUE TITLE
[mso_schema_site_anp_epg_staticport]Fails to find ANP/AP that is a part of Playbook

### ISSUE THREAD

**Issue by kmrobert** [CiscoDevNet/ansible-mso#88]
As you can see from the failure message below on the final task, the module is failing to assign the static port after failing to find the AP/ANP, which the first task in the playbook creates.

I also get the same error if I create the AP in the GUI and try the assignment through a playbook.

*******@kr_dev_ansible_dev:~/Playbooks$ ansible-playbook 02_MSO_ANP_EPG.yml 

PLAY [playbook to configure interface policy groups profiles and selectors] *******************************************************************************************

TASK [Add a new AP to DC] ********************************************************************************************************************************************
changed: [192.168.*.* -> localhost]

TASK [Add a new BD] ***************************************************************************************************************************************************
changed: [192.168.*.* -> localhost]

TASK [Add a new EPG] **************************************************************************************************************************************************
changed: [192.168.*.* -> localhost]

TASK [Add a new EPG] **************************************************************************************************************************************************
changed: [192.168.*.* -> localhost]

TASK [Add a new static port to a site EPG] ****************************************************************************************************************************
fatal: [192.168.*.* -> localhost]: **FAILED! => {"changed": false, "current": {}, "msg": "Provided anp 'MAN_AP' does not exist. Existing anps: "}**

PLAY RECAP ************************************************************************************************************************************************************
192.168.*.*            : ok=4    changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by lhercot** [comment]
Hi @kmrobert , can you provide the playbook you used for this?

Also are you using the latest version of the collection? 
We have made some changes there but you might still have to call the cisco.mso.mso_schema_site_anp before being able to add this static port.

Kind regards,

**Comment by kmrobert** [comment]
Hi Ihercot, thank you for coming back to me, I have now figured it out and I think it may be a bug, but perhaps you could let me know.

When the AP/ANP is created, using any method: API, Ansible or GUI, until there is an object consuming it i.e. and interface assigned, then the MSO has no ANPs that can be called or referred to, once an interface is assigned, if you query the AP/ANPs, it will then return the value created and a playbook can consume them.

I hope this makes sense, if not please let me know and I can try and clarify further, and just for reference my playbook is as per below:

---
- name: playbook to configure interface policy groups profiles and selectors
  hosts: mso
  gather_facts: no
  tasks:

    - name: Add a new AP to DC
      mso_schema_template_anp:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no
        schema: MAN
        template: DC_DC
        anp: "MAN_AP"
        state: present
      delegate_to: localhost

    - name: Add a new site ANP
      mso_schema_site_anp:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no
        schema: MAN
        site: Someco-stp-ndc-site1
        template: DC_DC
        anp: MAN_AP
        state: present
        delegate_to: localhost

    - name: Add a new BD
      mso_schema_template_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no
        schema: MAN
        template: DC_DC
        bd: VL_11_ST_BD
        display_name: VL_11_ST_BD
        layer2_unknown_unicast: flood
        layer2_stretch: no
        intersite_bum_traffic: no
        optimize_wan_bandwidth: no
        output_level: debug
        vrf: 
          name: MAN_VRF
        state: present
      delegate_to: localhost

    - name: Add a new EPG
      mso_schema_template_anp_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no 
        schema: MAN
        template: DC_DC
        anp: MAN_AP
        epg: VL_11_ST_EPG
        display_name: VL_11_ST_EPG
        bd:
          name: VL_11_ST_BD
        state: present
      delegate_to: localhost

    - name: Add a new EPG
      mso_schema_template_anp_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no 
        schema: MAN
        template: DC_DC
        anp: MAN_AP
        epg: VL_111_ST_EPG
        display_name: VL_111_ST_EPG
        bd:
          name: VL_11_ST_BD
        state: present
      delegate_to: localhost 

    - name: Add a domain to a site EPG
      mso_schema_site_anp_epg_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no
        schema: MAN
        site: Someco-stp-ndc-site1
        template: DC_DC
        anp: MAN_AP
        epg: VL_11_ST_EPG
        domain_association_type: physicalDomain
        domain_profile: 'MAN_PDOM'
        deployment_immediacy: immediate
        resolution_immediacy: pre-provision
        state: present
      delegate_to: localhost
    
    - name: Add a domain to a site EPG
      mso_schema_site_anp_epg_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no
        schema: MAN
        site: Someco-stp-ndc-site1
        template: DC_DC
        anp: MAN_AP
        epg: VL_11_ST_EPG
        domain_association_type: physicalDomain
        domain_profile: 'MAN_PDOM'
        deployment_immediacy: immediate
        resolution_immediacy: pre-provision
        state: present
      delegate_to: localhost

    - name: Add a new static port to a site EPG
      mso_schema_site_anp_epg_staticport:
        host: "{{ inventory_hostname }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        validate_certs: no        
        schema: MAN
        anp: MAN_AP
        site: Someco-stp-ndc-site1
        template: DC_DC
        epg: VL_111_ST_EPG
        type: port
        pod: pod-1
        leaf: '101'
        path: eth1/38
        vlan: 111
        deployment_immediacy: immediate
        state: present
      delegate_to: localhost

**Comment by kmrobert** [comment]
@Ihercot Please see above, apologies forgot to Tag.

**Comment by kmrobert** [comment]
Also to be clear, this issue is with the MSO, not Ansible, as I saw exactly the same issue using APIs with Postman.

**Comment by lhercot** [comment]
The way the MSO schema works is that when you create something at template level, it does not automatically creates it at Site level. The UI let you think it does but as you said until you modify something the sites portion under the schema is empty.

We fixed that partially recently in this collection (specifically in the mso_schema_site_anp_epg_domain) so if you update your installation to use the collection set of modules and not the one shipped with ansible, you will be able to make this playbook work.

For that, you need to first install the latest version of this collection.
First check your ansible version:
```
# ansible --version 
ansible 2.9.9
  config file = None
  configured module search path = ['/Users/lhercot/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lhercot/GIT/ansible/CiscoDevNet/venv-ansible-2.9/lib/python3.7/site-packages/ansible
  executable location = /Users/lhercot/GIT/ansible/CiscoDevNet/venv-ansible-2.9/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```
You will need at least version 2.9 so if not update your ansible version.
If you have version 2.9 or above, run the following command:
`ansible-galaxy collection install cisco.mso
`
You may want to add the --force attribute if you already have a version of this collection installed.
Last part, you need to append 'cisco.mso.' to each of the module calls like:
```
- name: Add a new AP to DC
  cisco.mso.mso_schema_template_anp:
    host: "{{ inventory_hostname }}"
    username: "{{ mso_username }}"
    password: "{{ mso_password }}"
    validate_certs: no
    schema: MAN
    template: DC_DC
    anp: "MAN_AP"
    state: present
  delegate_to: localhost
```
Let me know if this fix the problem.

**Comment by kmrobert** [comment]
@lhercot That collection has fixed the issue, thank you.
