### ISSUE TITLE
New module to support BD migrate feature 

### ISSUE THREAD

**Issue by amhunt-at-cisco** [CiscoDevNet/ansible-mso#89]
MSO supports migrating a BD between templates with a unique API call, however a new module would need to be written to support that with Ansible. This would be an enhancement - please reach out to amhunt@cisco.com for details. 

Customer_request_label would be amhunt@cisco.com

**Comment by sacascio** [comment]
@lhercot do you know when this feature will be available?

**Comment by lhercot** [comment]
Hi Salvatore,

This enhancement is now in our sprint pipeline so it should be implemented in the next 2-3 weeks.

Kind regards,

[http://www.cisco.com/c/dam/m/en_us/signaturetool/images/banners/standard/01_standard_ciscoblue.png]
Lionel Hercot
Technical Marketing Engineer
Product Development
lhercot@cisco.com<mailto:lhercot@cisco.com>
Tel: +1 408 525 4824
Mobile: +1 408 410 7594
Cisco Systems, Inc.
3625 Cisco Way
San Jose, California 95134
United States
Cisco.com<http://www.cisco.com/>
Download vCard<http://wwwin-tools.cisco.com/dir/vcard/undefined.vcf>
[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif]
Think before you print.
This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/c/en/us/about/legal/terms-sale-software-license-agreement/company-registration-information.html> for Company Registration Information.
