### ISSUE TITLE
[mso_schema_site_bd_subnet] Site BD subnet is not being pushed to APIC after deployment

### ISSUE THREAD

**Issue by kentwu1** [CiscoDevNet/ansible-mso#93]
I can use mso_schema_site_bd_subnet module to configure site BD subnet, it would show up in MSO np. However that BD subnet is not being pushed to APIC after schema deployment....If I manually deleted that site BD subnet, added it back thru MSO, then it will show up in APIC after deployment so looks like there is something missing with this mso_schema_site_bd_subnet.

**Comment by xinyuezhao** [comment]
@kentwu1 
In order to push site BD subnet to APIC, we have to disable layer2_stretch in template BD before creating a site BD subnet.
To disable layer2_stretch, we can use mso_schema_template_bd module, setting layer2_stretch attribute as false.

The following are simple examples which you may need.

- name: Disable layer2_stretch in template BD
  mso_schema_template_bd:
    <<: *mso_info
    schema: '{{ mso_schema | default("ansible_test") }}'
    template: Template 1
    bd: ansible_test_1
    layer2_stretch: false
    vrf:
      name: VRF1
    state: present
  register: nm_add_bd

- name: Add site BD subnet with layer2_stretch disabled (normal_mode)
  mso_schema_site_bd_subnet:
    <<: *mso_info
    schema: '{{ mso_schema | default("ansible_test") }}'
    site: '{{ mso_site | default("ansible_test") }}'
    template: Template 1
    bd: ansible_test_1
    subnet: 10.1.0.1/16
    state: present
  register: nm_add_site_bd_subnet

**Comment by xinyuezhao** [comment]
btw, we also fix the issue of deploy module so that now you can use our mso_schema_template_deploy module to do the template deployment.

examples you may want: 

- name: Deploy templates
  mso_schema_template_deploy:
    <<: *schema_deploy
    schema: ansible_test
    template: "{{ item }}"
    site: '{{ mso_site | default("ansible_test") }}'
    state: deploy
  register: nm_deploy_template
  loop:
  - Template 1
  - Template 2

**Comment by kentwu1** [comment]
Hi I checked my MSO policy and the layer2_stretch is already disabled in the BD though. I think the default is to disable so. But I see you also submitted a patch to fix something so I assume once that patch is merged, this issue will be resolved also? Thx.

**Comment by kentwu1** [comment]
Also how do I get the latest MSO modules once your patch is merged?

**Comment by xinyuezhao** [comment]
Hi did you create template BD by our module?  if so, would you mind share the task you use to create that template BD?

And my fix is just an error out when user want to create a site BD subnet but the layer2_stretch is enabled.

**Comment by xinyuezhao** [comment]
As for the lastest version of our code, you can git pull from our repo or wait for our next release which might be Tuesday this week.

**Comment by kentwu1** [comment]
Below is the code I used to create the template BD. Let me know if something is still missing then.

- name: Add a BD to Fab2 template
    mso_schema_template_bd:
      host: "{{ mso_host }}"
      username: "{{ user }}"
      password: "{{ passwd }}"
      schema: "{{ schema }}"
      template: Fab2
      bd: aci-containers-k8s_c2f2-node-bd
      layer2_unknown_unicast: proxy
      vrf:
        template: Common
        name: K8S
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no

**Comment by xinyuezhao** [comment]
Currently in our module the default value of layer2_stretch is 'None' instead of 'false' when we don't set anything to it. 

We'll discuss to see whether we make this layer2_stretch field required or use any other way to fix it.

Will get back to you soon once we fix it.

**Comment by kentwu1** [comment]
Ah I see. In that case I can set it to false np. But I wonder why if I manually delete that site BD subnet then add it back, then deploy the template again, then that site BD subnet will show up in APIC?

**Comment by xinyuezhao** [comment]
I suppose in UI, if you want to create a site BD subnet manually, you may need to uncheck the checkbox for l2Stretch in template BD. At that time, you set the l2Stretch as 'false'.

**Comment by kentwu1** [comment]
Tried it & it works once layer2_stretch was set to false so its good now. Regarding your release this Thursday, do I have to upgrade the ansible to get that or it will download the latest automatically? Not that familiar with how the updated MSO modules are being distributed so....Thx.

**Comment by lhercot** [comment]
Which version of Ansible do you use? You should move to use the ansible collection and then you can simply upgrade using ansible-galaxy commands when we release them to galaxy.
You will have to prepend "cisco.mso." to the module calls such as cisco.mso.mso_schema_site_bd_subnet.

**Comment by kentwu1** [comment]
I was able to use "ansible-galaxy collection install cisco-mso-1.0.0.tar.gz —force" to upgrade so its all good now. Thx.
