### ISSUE TITLE
mso_schema_site_anp_epg_staticport

### ISSUE THREAD

**Issue by amass87** [CiscoDevNet/ansible-mso#97]
Missing options for Port-channel and VPC.  I added an option for VPC, but haven't successfully added port-channel type yet.
[mso_schema_site_anp_epg_staticport.py.zip](https://github.com/CiscoDevNet/ansible-mso/files/5091477/mso_schema_site_anp_epg_staticport.py.zip)

**Comment by lhercot** [comment]
Hi @amass87 

We added support for both vPC and Direct Port Channel a few weeks ago, please check the following PRs: 
- https://github.com/CiscoDevNet/ansible-mso/pull/56
- https://github.com/CiscoDevNet/ansible-mso/pull/37

So if you can try again using the latest cisco.mso collection from Galaxy that would be great to let us know if this fits your need.

**Comment by amass87** [comment]
I don’t see this functionality in the latest version of the module.  Please confirm this was committed to the collection.  I have downloaded release 1.0.0.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lhercot** [comment]
Yes it is included as you can see that those were merged a few weeks back.

Here is what I see in the documentation for the module in v1.0.0:
$ ansible-doc cisco.mso.mso_schema_site_anp_epg_staticport
- type
        The path type of the static port
        vpc is used for a Virtual Port Channel
        dpc is used for a Direct Port Channel
        port is used for a single interface
        (Choices: port, vpc, dpc)[Default: port]
        type: str

Make sure you call the collection module by using the FQCN (cisco.mso.MODULE_NAME) as you might still be using the module from ansible core which is not up to date.

**Comment by amass87** [comment]
I just installed the collection 4 days ago, version 1.0.0 from ansible galaxy.  It was still missing when I checked tested it and checked the python module.  Let me to get the collection again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amass87** [comment]
Lionel,

I am sure you might be tired of hearing this, but you were right.  I went back and checked the particular task where I call this module.  It looks like I was missing the cisco.mso. in the module reference.  It's been a long week, please mark this duplicate and resolved.

Regards,
Ajay
________________________________

**Comment by lhercot** [comment]
No problem. Let us know if you have any other issues.
